# Dataset Evaluation: Clean vs Poisoned Data

This notebook evaluates simple sklearn models on:
- Clean datasets
- AR (At Random) poisoned datasets
- NAR (Not At Random) poisoned datasets

We test 3-4 efficient classifiers/regressors and measure performance degradation across multiple random seeds (42-46) using parallelized testing with joblib.

In [1]:
import pandas as pd
import numpy as np
import warnings
from joblib import Parallel, delayed
from sklearn.metrics import accuracy_score, f1_score, mean_squared_error, r2_score

# Models
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.linear_model import LogisticRegression, Ridge
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor
from sklearn.neighbors import KNeighborsClassifier, KNeighborsRegressor

# Import data loading utilities
import sys
sys.path.insert(0, '..')
from frogdq.data import get_datasets, load_data

warnings.filterwarnings("ignore")

## Configuration

In [2]:
# Test seeds to use
SEEDS = list(range(42, 47))  # Seeds 42 to 46

# Data modes to test
MODES = ["clean", "ar", "nar"]

# Number of parallel jobs for joblib
N_JOBS = -1  # Use all available cores

print(f"Testing on seeds: {SEEDS}")
print(f"Testing modes: {MODES}")
print(f"Parallel jobs: {N_JOBS if N_JOBS > 0 else 'all cores'}")

Testing on seeds: [42, 43, 44, 45, 46]
Testing modes: ['clean', 'ar', 'nar']
Parallel jobs: all cores

## Load Available Datasets

In [4]:
# Get list of all available datasets
datasets_df = get_datasets(data_dir="../data", poisoned_dir="../data_poisoned")

# Filter to only datasets that have both AR and NAR poisoned versions
available_datasets = datasets_df[
    (datasets_df["has_ar"] == True) & (datasets_df["has_nar"] == True)
].copy()

print(f"Found {len(available_datasets)} datasets with all poisoning modes")
print(f"\nDatasets to evaluate:")
display(available_datasets[['dataset_name', 'task_type', 'n_samples', 'n_features', 'n_classes']])

Found 50 datasets with all poisoning modes

Datasets to evaluate:

,dataset_name,task_type,n_samples,n_features,n_classes
0,iris,classification,150,4,3
1,heart_disease,regression,303,13,0
2,wine_quality,regression,6497,11,0
3,breast_cancer_wisconsin_diagnostic,classification,569,30,2
4,bank_marketing,classification,45211,16,2
5,adult,classification,48842,14,4
6,wine,classification,178,13,3
7,car_evaluation,classification,1728,6,4
8,predict_students_dropout_and_academic_success,classification,4424,36,3
9,default_of_credit_card_clients,classification,30000,23,2
10,automobile,regression,205,25,0
11,mushroom,classification,8124,22,2
12,statlog_german_credit_data,classification,1000,20,2
13,abalone,regression,4177,8,0
14,bike_sharing,regression,17379,13,0
15,estimation_of_obesity_levels_based_on_eating_h...,classification,2111,16,7
16,auto_mpg,regression,398,7,0
17,spambase,classification,4601,57,2
18,online_shoppers_purchasing_intention_dataset,classification,12330,17,2
19,magic_gamma_telescope,classification,19020,10,2
20,breast_cancer_wisconsin_original,classification,699,9,2
21,forest_fires,regression,517,12,0
22,breast_cancer,classification,286,9,2
23,dry_bean,classification,13611,16,7
24,heart_failure_clinical_records,classification,299,12,2
25,credit_approval,classification,690,15,2
26,real_estate_valuation,regression,414,6,0
27,chronic_kidney_disease,classification,400,24,3
28,concrete_compressive_strength,regression,1030,8,0
29,wholesale_customers,classification,440,7,3
30,parkinsons,regression,195,22,0
31,seoul_bike_sharing_demand,classification,8760,13,2
32,rice_cammeo_and_osmancik,classification,3810,7,2
33,optical_recognition_of_handwritten_digits,classification,5620,64,10
34,glass_identification,classification,214,9,6
35,phishing_websites,regression,11055,30,0
36,appliances_energy_prediction,regression,19735,28,0
37,banknote_authentication,regression,1372,4,0
38,zoo,classification,101,16,7
39,higher_education_students_performance_evaluation,classification,145,31,8
40,productivity_prediction_of_garment_employees,regression,1197,14,0
41,maternal_health_risk,classification,1014,6,3
42,early_stage_diabetes_risk_prediction,classification,520,16,2
43,letter_recognition,classification,20000,16,26
44,combined_cycle_power_plant,regression,9568,4,0
45,liver_disorders,regression,345,5,0
46,national_poll_on_healthy_aging_npha,classification,714,14,3
47,hepatitis,classification,155,19,2
48,aids_clinical_trials_group_study_175,classification,2139,23,2
49,iranian_churn,classification,3150,13,2

## Model Selection Functions

In [5]:
def get_models(task_type, seed=42):
    """Get simple, efficient models for the task with specific seed."""
    if task_type == "classification":
        return {
            "LogisticRegression": LogisticRegression(max_iter=1000, random_state=seed),
            "DecisionTree": DecisionTreeClassifier(max_depth=10, random_state=seed),
            "RandomForest": RandomForestClassifier(
                n_estimators=100, max_depth=10, random_state=seed, n_jobs=1
            ),
            "KNN": KNeighborsClassifier(n_neighbors=5, n_jobs=1),
        }
    else:  # regression
        return {
            "Ridge": Ridge(random_state=seed),
            "DecisionTree": DecisionTreeRegressor(max_depth=10, random_state=seed),
            "RandomForest": RandomForestRegressor(
                n_estimators=100, max_depth=10, random_state=seed, n_jobs=1
            ),
            "KNN": KNeighborsRegressor(n_neighbors=5, n_jobs=1),
        }


def evaluate_model(model, X_train, X_test, y_train, y_test, task_type):
    """Train and evaluate a single model."""
    try:
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)

        if task_type == "classification":
            acc = accuracy_score(y_test, y_pred)
            f1 = f1_score(y_test, y_pred, average="weighted", zero_division=0)
            return {"accuracy": acc, "f1_score": f1}
        else:  # regression
            mse = mean_squared_error(y_test, y_pred)
            r2 = r2_score(y_test, y_pred)
            return {"mse": mse, "r2_score": r2}
    except Exception as e:
        print(f"Error evaluating model: {e}")
        if task_type == "classification":
            return {"accuracy": 0.0, "f1_score": 0.0}
        else:
            return {"mse": float("inf"), "r2_score": -float("inf")}

## Evaluation Function with Parallelization

In [8]:
def evaluate_single_configuration(dataset_name, mode, seed, task_type):
    """Evaluate all models for a single dataset-mode-seed configuration."""
    results = []
    
    try:
        # Load data using the data.py utilities
        # Always use clean test set for fair comparison
        (X_train, X_val, X_test), (y_train, y_val, y_test), preprocessor, metadata = load_data(
            dataset_name=dataset_name,
            mode=mode,
            seed=seed,
            clean_val=True,  # Use clean validation
            clean_test=True,  # Use clean test for fair comparison
            data_dir="../data",
            poisoned_dir="../data_poisoned",
        )
        
        # Get models for this task type and seed
        models = get_models(task_type, seed=seed)
        
        # Evaluate each model
        for model_name, model in models.items():
            metrics = evaluate_model(model, X_train, X_test, y_train, y_test, task_type)
            
            results.append({
                "dataset": dataset_name,
                "task_type": task_type,
                "data_mode": mode,
                "seed": seed,
                "model": model_name,
                "overall_quality": metadata["overall_quality"],
                "train_samples": metadata["n_samples"]["train"],
                "test_samples": metadata["n_samples"]["test"],
                **metrics,
            })
        
        return results
    
    except Exception as e:
        print(f"Error processing {dataset_name} (mode={mode}, seed={seed}): {e}")
        return []


def evaluate_dataset(dataset_name, task_type, seeds, modes, n_jobs=-1):
    """Evaluate a dataset across all seeds and modes using parallel processing."""
    print(f"\nEvaluating {dataset_name} ({task_type})...")
    
    # Create all configurations to test
    configurations = [
        (dataset_name, mode, seed, task_type)
        for mode in modes
        for seed in seeds
    ]
    
    # Run evaluations in parallel
    all_results = Parallel(n_jobs=n_jobs, verbose=0)(
        delayed(evaluate_single_configuration)(*config)
        for config in configurations
    )
    
    # Flatten results
    results = []
    for result_list in all_results:
        results.extend(result_list)
    
    return results

## Run Evaluation on All Datasets

In [9]:
# Collect all results
all_results = []

for _, row in available_datasets.iterrows():
    dataset_name = row["dataset_name"]
    task_type = row["task_type"]
    
    results = evaluate_dataset(
        dataset_name=dataset_name,
        task_type=task_type,
        seeds=SEEDS,
        modes=MODES,
        n_jobs=N_JOBS,
    )
    
    all_results.extend(results)

# Create results dataframe
results_df = pd.DataFrame(all_results)
print(f"\n{'='*60}")
print(f"Evaluation complete! Processed {len(results_df)} model runs")
print(f"Total datasets: {len(available_datasets)}")
print(f"Seeds per dataset: {len(SEEDS)}")
print(f"Modes per dataset: {len(MODES)}")
print(f"{'='*60}")

Evaluating iris (classification)...
Detected task type: classification
Detected 4 numerical features: ['num_sepal length', 'num_sepal width', 'num_petal length', 'num_petal width']
Detected 0 categorical features: []
Detected task type: classification
Detected 4 numerical features: ['num_sepal length', 'num_sepal width', 'num_petal length', 'num_petal width']
Detected 0 categorical features: []
Detected task type: classification
Detected task type: classification
Detected 4 numerical features: ['num_sepal length', 'num_sepal width', 'num_petal length', 'num_petal width']
Detected 0 categorical features: []
Detected 4 numerical features: ['num_sepal length', 'num_sepal width', 'num_petal length', 'num_petal width']
Detected 0 categorical features: []
Detected task type: classification
Detected 4 numerical features: ['num_sepal length', 'num_sepal width', 'num_petal length', 'num_petal width']
Detected 0 categorical features: []
Detected task type: classification
Detected 4 numerical features: ['num_sepal length', 'num_sepal width', 'num_petal length', 'num_petal width']
Detected 0 categorical features: []
Detected task type: classification
Detected 4 numerical features: ['num_sepal length', 'num_sepal width', 'num_petal length', 'num_petal width']
Detected 0 categorical features: []
Detected task type: classification
Detected 4 numerical features: ['num_sepal length', 'num_sepal width', 'num_petal length', 'num_petal width']
Detected 0 categorical features: []
Detected task type: classification
Detected 4 numerical features: ['num_sepal length', 'num_sepal width', 'num_petal length', 'num_petal width']
Detected 0 categorical features: []
Detected task type: classification
Detected 4 numerical features: ['num_sepal length', 'num_sepal width', 'num_petal length', 'num_petal width']
Detected 0 categorical features: []
Detected task type: classification
Detected 4 numerical features: ['num_sepal length', 'num_sepal width', 'num_petal length', 'num_petal width']
Detected 0 categorical features: []
Detected task type: classification
Detected 4 numerical features: ['num_sepal length', 'num_sepal width', 'num_petal length', 'num_petal width']
Detected 0 categorical features: []
Detected task type: classification
Detected 4 numerical features: ['num_sepal length', 'num_sepal width', 'num_petal length', 'num_petal width']
Detected 0 categorical features: []
Detected task type: classification
Detected 4 numerical features: ['num_sepal length', 'num_sepal width', 'num_petal length', 'num_petal width']
Detected 0 categorical features: []
Detected task type: classification
Detected 4 numerical features: ['num_sepal length', 'num_sepal width', 'num_petal length', 'num_petal width']
Detected 0 categorical features: []

Evaluating heart_disease (regression)...
Detected task type: classification
Detected 6 numerical features: ['num_age', 'num_trestbps', 'num_chol', 'num_thalach', 'num_oldpeak']...
Detected 7 categorical features: ['cat_sex', 'cat_cp', 'cat_fbs', 'cat_restecg', 'cat_exang']...
Detected task type: classification
Detected 6 numerical features: ['num_age', 'num_trestbps', 'num_chol', 'num_thalach', 'num_oldpeak']...
Detected 7 categorical features: ['cat_sex', 'cat_cp', 'cat_fbs', 'cat_restecg', 'cat_exang']...
Detected task type: classification
Detected 6 numerical features: ['num_age', 'num_trestbps', 'num_chol', 'num_thalach', 'num_oldpeak']...
Detected 7 categorical features: ['cat_sex', 'cat_cp', 'cat_fbs', 'cat_restecg', 'cat_exang']...
Detected task type: classification
Detected 6 numerical features: ['num_age', 'num_trestbps', 'num_chol', 'num_thalach', 'num_oldpeak']...
Detected 7 categorical features: ['cat_sex', 'cat_cp', 'cat_fbs', 'cat_restecg', 'cat_exang']...
Detected task type: classification
Detected 6 numerical features: ['num_age', 'num_trestbps', 'num_chol', 'num_thalach', 'num_oldpeak']...
Detected 7 categorical features: ['cat_sex', 'cat_cp', 'cat_fbs', 'cat_restecg', 'cat_exang']...
Detected task type: classification
Detected 6 numerical features: ['num_age', 'num_trestbps', 'num_chol', 'num_thalach', 'num_oldpeak']...
Detected 7 categorical features: ['cat_sex', 'cat_cp', 'cat_fbs', 'cat_restecg', 'cat_exang']...
Detected task type: classification
Detected 6 numerical features: ['num_age', 'num_trestbps', 'num_chol', 'num_thalach', 'num_oldpeak']...
Detected 7 categorical features: ['cat_sex', 'cat_cp', 'cat_fbs', 'cat_restecg', 'cat_exang']...

/home/aarchetto/frog-dq/notebooks/../frogdq/preprocessing.py:323: FutureWarning: Downcasting behavior in Series and DataFrame methods 'where', 'mask', and 'clip' is deprecated. In a future version this will not infer object dtypes or cast all-round floats to integers. Instead call result.infer_objects(copy=False) for object inference, or cast round floats explicitly. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X[col] = X[col].clip(lower, upper).infer_objects(copy=False)
/home/aarchetto/frog-dq/notebooks/../frogdq/preprocessing.py:323: FutureWarning: Downcasting behavior in Series and DataFrame methods 'where', 'mask', and 'clip' is deprecated. In a future version this will not infer object dtypes or cast all-round floats to integers. Instead call result.infer_objects(copy=False) for object inference, or cast round floats explicitly. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X[col] = X[col].clip(lower, upper).infer_objects(copy=False)
/home/aarchetto/frog-dq/notebooks/../frogdq/preprocessing.py:323: FutureWarning: Downcasting behavior in Series and DataFrame methods 'where', 'mask', and 'clip' is deprecated. In a future version this will not infer object dtypes or cast all-round floats to integers. Instead call result.infer_objects(copy=False) for object inference, or cast round floats explicitly. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X[col] = X[col].clip(lower, upper).infer_objects(copy=False)
/home/aarchetto/frog-dq/notebooks/../frogdq/preprocessing.py:323: FutureWarning: Downcasting behavior in Series and DataFrame methods 'where', 'mask', and 'clip' is deprecated. In a future version this will not infer object dtypes or cast all-round floats to integers. Instead call result.infer_objects(copy=False) for object inference, or cast round floats explicitly. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X[col] = X[col].clip(lower, upper).infer_objects(copy=False)

Detected task type: classification
Detected 6 numerical features: ['num_age', 'num_trestbps', 'num_chol', 'num_thalach', 'num_oldpeak']...
Detected 7 categorical features: ['cat_sex', 'cat_cp', 'cat_fbs', 'cat_restecg', 'cat_exang']...
Detected task type: classification
Detected 6 numerical features: ['num_age', 'num_trestbps', 'num_chol', 'num_thalach', 'num_oldpeak']...
Detected 7 categorical features: ['cat_sex', 'cat_cp', 'cat_fbs', 'cat_restecg', 'cat_exang']...
Detected task type: classification
Detected 6 numerical features: ['num_age', 'num_trestbps', 'num_chol', 'num_thalach', 'num_oldpeak']...
Detected 7 categorical features: ['cat_sex', 'cat_cp', 'cat_fbs', 'cat_restecg', 'cat_exang']...
Detected task type: classification
Detected 6 numerical features: ['num_age', 'num_trestbps', 'num_chol', 'num_thalach', 'num_oldpeak']...
Detected 7 categorical features: ['cat_sex', 'cat_cp', 'cat_fbs', 'cat_restecg', 'cat_exang']...
Detected task type: classification
Detected 6 numerical features: ['num_age', 'num_trestbps', 'num_chol', 'num_thalach', 'num_oldpeak']...
Detected 7 categorical features: ['cat_sex', 'cat_cp', 'cat_fbs', 'cat_restecg', 'cat_exang']...
Detected task type: classification
Detected 6 numerical features: ['num_age', 'num_trestbps', 'num_chol', 'num_thalach', 'num_oldpeak']...
Detected 7 categorical features: ['cat_sex', 'cat_cp', 'cat_fbs', 'cat_restecg', 'cat_exang']...
Detected task type: classification
Detected 6 numerical features: ['num_age', 'num_trestbps', 'num_chol', 'num_thalach', 'num_oldpeak']...
Detected 7 categorical features: ['cat_sex', 'cat_cp', 'cat_fbs', 'cat_restecg', 'cat_exang']...
Detected task type: classification
Detected 6 numerical features: ['num_age', 'num_trestbps', 'num_chol', 'num_thalach', 'num_oldpeak']...
Detected 7 categorical features: ['cat_sex', 'cat_cp', 'cat_fbs', 'cat_restecg', 'cat_exang']...

Evaluating wine_quality (regression)...
Detected task type: classification
Detected 11 numerical features: ['num_fixed_acidity', 'num_volatile_acidity', 'num_citric_acid', 'num_residual_sugar', 'num_chlorides']...
Detected 0 categorical features: []
Detected task type: classification
Detected 11 numerical features: ['num_fixed_acidity', 'num_volatile_acidity', 'num_citric_acid', 'num_residual_sugar', 'num_chlorides']...
Detected 0 categorical features: []
Detected task type: classification
Detected 11 numerical features: ['num_fixed_acidity', 'num_volatile_acidity', 'num_citric_acid', 'num_residual_sugar', 'num_chlorides']...
Detected 0 categorical features: []
Detected task type: classification
Detected 11 numerical features: ['num_fixed_acidity', 'num_volatile_acidity', 'num_citric_acid', 'num_residual_sugar', 'num_chlorides']...
Detected 0 categorical features: []
Detected task type: classification
Detected 11 numerical features: ['num_fixed_acidity', 'num_volatile_acidity', 'num_citric_acid', 'num_residual_sugar', 'num_chlorides']...
Detected 0 categorical features: []
Detected task type: classification
Detected 11 numerical features: ['num_fixed_acidity', 'num_volatile_acidity', 'num_citric_acid', 'num_residual_sugar', 'num_chlorides']...
Detected 0 categorical features: []
Detected task type: classification
Detected 11 numerical features: ['num_fixed_acidity', 'num_volatile_acidity', 'num_citric_acid', 'num_residual_sugar', 'num_chlorides']...
Detected 0 categorical features: []
Detected task type: classification
Detected 11 numerical features: ['num_fixed_acidity', 'num_volatile_acidity', 'num_citric_acid', 'num_residual_sugar', 'num_chlorides']...
Detected 0 categorical features: []
Detected task type: classification
Detected 11 numerical features: ['num_fixed_acidity', 'num_volatile_acidity', 'num_citric_acid', 'num_residual_sugar', 'num_chlorides']...
Detected 0 categorical features: []
Detected task type: classification
Detected 11 numerical features: ['num_fixed_acidity', 'num_volatile_acidity', 'num_citric_acid', 'num_residual_sugar', 'num_chlorides']...
Detected 0 categorical features: []
Detected task type: classification
Detected 11 numerical features: ['num_fixed_acidity', 'num_volatile_acidity', 'num_citric_acid', 'num_residual_sugar', 'num_chlorides']...
Detected 0 categorical features: []
Detected task type: classification
Detected 11 numerical features: ['num_fixed_acidity', 'num_volatile_acidity', 'num_citric_acid', 'num_residual_sugar', 'num_chlorides']...
Detected 0 categorical features: []
Detected task type: classification
Detected 11 numerical features: ['num_fixed_acidity', 'num_volatile_acidity', 'num_citric_acid', 'num_residual_sugar', 'num_chlorides']...
Detected 0 categorical features: []
Detected task type: classification
Detected 11 numerical features: ['num_fixed_acidity', 'num_volatile_acidity', 'num_citric_acid', 'num_residual_sugar', 'num_chlorides']...
Detected 0 categorical features: []
Detected task type: classification
Detected 11 numerical features: ['num_fixed_acidity', 'num_volatile_acidity', 'num_citric_acid', 'num_residual_sugar', 'num_chlorides']...
Detected 0 categorical features: []

Evaluating breast_cancer_wisconsin_diagnostic (classification)...
Detected task type: classification
Detected 30 numerical features: ['num_radius1', 'num_texture1', 'num_perimeter1', 'num_area1', 'num_smoothness1']...
Detected 0 categorical features: []
Detected task type: classification
Detected 30 numerical features: ['num_radius1', 'num_texture1', 'num_perimeter1', 'num_area1', 'num_smoothness1']...
Detected 0 categorical features: []
Detected task type: classification
Detected 30 numerical features: ['num_radius1', 'num_texture1', 'num_perimeter1', 'num_area1', 'num_smoothness1']...
Detected 0 categorical features: []
Detected task type: classification
Detected 30 numerical features: ['num_radius1', 'num_texture1', 'num_perimeter1', 'num_area1', 'num_smoothness1']...
Detected 0 categorical features: []
Detected task type: classification
Detected 30 numerical features: ['num_radius1', 'num_texture1', 'num_perimeter1', 'num_area1', 'num_smoothness1']...
Detected 0 categorical features: []
Detected task type: classification
Detected 30 numerical features: ['num_radius1', 'num_texture1', 'num_perimeter1', 'num_area1', 'num_smoothness1']...
Detected 0 categorical features: []
Detected task type: classification
Detected 30 numerical features: ['num_radius1', 'num_texture1', 'num_perimeter1', 'num_area1', 'num_smoothness1']...
Detected 0 categorical features: []
Detected task type: classification
Detected 30 numerical features: ['num_radius1', 'num_texture1', 'num_perimeter1', 'num_area1', 'num_smoothness1']...
Detected 0 categorical features: []
Detected task type: classification
Detected 30 numerical features: ['num_radius1', 'num_texture1', 'num_perimeter1', 'num_area1', 'num_smoothness1']...
Detected 0 categorical features: []
Detected task type: classification
Detected 30 numerical features: ['num_radius1', 'num_texture1', 'num_perimeter1', 'num_area1', 'num_smoothness1']...
Detected 0 categorical features: []
Detected task type: classification
Detected 30 numerical features: ['num_radius1', 'num_texture1', 'num_perimeter1', 'num_area1', 'num_smoothness1']...
Detected 0 categorical features: []
Detected task type: classification
Detected 30 numerical features: ['num_radius1', 'num_texture1', 'num_perimeter1', 'num_area1', 'num_smoothness1']...
Detected 0 categorical features: []
Detected task type: classification
Detected 30 numerical features: ['num_radius1', 'num_texture1', 'num_perimeter1', 'num_area1', 'num_smoothness1']...
Detected 0 categorical features: []
Detected task type: classification
Detected 30 numerical features: ['num_radius1', 'num_texture1', 'num_perimeter1', 'num_area1', 'num_smoothness1']...
Detected 0 categorical features: []
Detected task type: classification
Detected 30 numerical features: ['num_radius1', 'num_texture1', 'num_perimeter1', 'num_area1', 'num_smoothness1']...
Detected 0 categorical features: []

Evaluating bank_marketing (classification)...
Detected task type: classification
Detected 6 numerical features: ['num_age', 'num_balance', 'num_duration', 'num_campaign', 'num_pdays']...
Detected 8 categorical features: ['cat_job', 'cat_marital', 'cat_education', 'cat_default', 'cat_housing']...
Detected 2 date features: ['dat_day_of_week', 'dat_month']
Detected task type: classification
Detected 6 numerical features: ['num_age', 'num_balance', 'num_duration', 'num_campaign', 'num_pdays']...
Detected 8 categorical features: ['cat_job', 'cat_marital', 'cat_education', 'cat_default', 'cat_housing']...
Detected 2 date features: ['dat_day_of_week', 'dat_month']
Detected task type: classification
Detected 6 numerical features: ['num_age', 'num_balance', 'num_duration', 'num_campaign', 'num_pdays']...
Detected 8 categorical features: ['cat_job', 'cat_marital', 'cat_education', 'cat_default', 'cat_housing']...
Detected 2 date features: ['dat_day_of_week', 'dat_month']
Detected task type: classification
Detected 6 numerical features: ['num_age', 'num_balance', 'num_duration', 'num_campaign', 'num_pdays']...
Detected 8 categorical features: ['cat_job', 'cat_marital', 'cat_education', 'cat_default', 'cat_housing']...
Detected 2 date features: ['dat_day_of_week', 'dat_month']
Detected task type: classification
Detected 6 numerical features: ['num_age', 'num_balance', 'num_duration', 'num_campaign', 'num_pdays']...
Detected 8 categorical features: ['cat_job', 'cat_marital', 'cat_education', 'cat_default', 'cat_housing']...
Detected 2 date features: ['dat_day_of_week', 'dat_month']
Detected task type: classification
Detected 6 numerical features: ['num_age', 'num_balance', 'num_duration', 'num_campaign', 'num_pdays']...
Detected 8 categorical features: ['cat_job', 'cat_marital', 'cat_education', 'cat_default', 'cat_housing']...
Detected 2 date features: ['dat_day_of_week', 'dat_month']
Detected task type: classification
Detected 6 numerical features: ['num_age', 'num_balance', 'num_duration', 'num_campaign', 'num_pdays']...
Detected 8 categorical features: ['cat_job', 'cat_marital', 'cat_education', 'cat_default', 'cat_housing']...
Detected 2 date features: ['dat_day_of_week', 'dat_month']
Detected task type: classification
Detected 6 numerical features: ['num_age', 'num_balance', 'num_duration', 'num_campaign', 'num_pdays']...
Detected 8 categorical features: ['cat_job', 'cat_marital', 'cat_education', 'cat_default', 'cat_housing']...
Detected 2 date features: ['dat_day_of_week', 'dat_month']
Detected task type: classification
Detected 6 numerical features: ['num_age', 'num_balance', 'num_duration', 'num_campaign', 'num_pdays']...
Detected 8 categorical features: ['cat_job', 'cat_marital', 'cat_education', 'cat_default', 'cat_housing']...
Detected 2 date features: ['dat_day_of_week', 'dat_month']
Detected task type: classification
Detected 6 numerical features: ['num_age', 'num_balance', 'num_duration', 'num_campaign', 'num_pdays']...
Detected 8 categorical features: ['cat_job', 'cat_marital', 'cat_education', 'cat_default', 'cat_housing']...
Detected 2 date features: ['dat_day_of_week', 'dat_month']
Detected task type: classification
Detected 6 numerical features: ['num_age', 'num_balance', 'num_duration', 'num_campaign', 'num_pdays']...
Detected 8 categorical features: ['cat_job', 'cat_marital', 'cat_education', 'cat_default', 'cat_housing']...
Detected 2 date features: ['dat_day_of_week', 'dat_month']
Detected task type: classification
Detected 6 numerical features: ['num_age', 'num_balance', 'num_duration', 'num_campaign', 'num_pdays']...
Detected 8 categorical features: ['cat_job', 'cat_marital', 'cat_education', 'cat_default', 'cat_housing']...
Detected 2 date features: ['dat_day_of_week', 'dat_month']
Detected task type: classification
Detected 6 numerical features: ['num_age', 'num_balance', 'num_duration', 'num_campaign', 'num_pdays']...
Detected 8 categorical features: ['cat_job', 'cat_marital', 'cat_education', 'cat_default', 'cat_housing']...
Detected 2 date features: ['dat_day_of_week', 'dat_month']
Detected task type: classification
Detected 6 numerical features: ['num_age', 'num_balance', 'num_duration', 'num_campaign', 'num_pdays']...
Detected 8 categorical features: ['cat_job', 'cat_marital', 'cat_education', 'cat_default', 'cat_housing']...
Detected 2 date features: ['dat_day_of_week', 'dat_month']
Detected task type: classification
Detected 6 numerical features: ['num_age', 'num_balance', 'num_duration', 'num_campaign', 'num_pdays']...
Detected 8 categorical features: ['cat_job', 'cat_marital', 'cat_education', 'cat_default', 'cat_housing']...
Detected 2 date features: ['dat_day_of_week', 'dat_month']

Evaluating adult (classification)...
Detected task type: classification
Detected 6 numerical features: ['num_age', 'num_fnlwgt', 'num_education-num', 'num_capital-gain', 'num_capital-loss']...
Detected 8 categorical features: ['cat_workclass', 'cat_education', 'cat_marital-status', 'cat_occupation', 'cat_relationship']...
Detected task type: classification
Detected 6 numerical features: ['num_age', 'num_fnlwgt', 'num_education-num', 'num_capital-gain', 'num_capital-loss']...
Detected 8 categorical features: ['cat_workclass', 'cat_education', 'cat_marital-status', 'cat_occupation', 'cat_relationship']...
Detected task type: classification
Detected 6 numerical features: ['num_age', 'num_fnlwgt', 'num_education-num', 'num_capital-gain', 'num_capital-loss']...
Detected 8 categorical features: ['cat_workclass', 'cat_education', 'cat_marital-status', 'cat_occupation', 'cat_relationship']...
Detected task type: classification
Detected 6 numerical features: ['num_age', 'num_fnlwgt', 'num_education-num', 'num_capital-gain', 'num_capital-loss']...
Detected 8 categorical features: ['cat_workclass', 'cat_education', 'cat_marital-status', 'cat_occupation', 'cat_relationship']...
Detected task type: classification
Detected 6 numerical features: ['num_age', 'num_fnlwgt', 'num_education-num', 'num_capital-gain', 'num_capital-loss']...
Detected 8 categorical features: ['cat_workclass', 'cat_education', 'cat_marital-status', 'cat_occupation', 'cat_relationship']...
Detected task type: classificationDetected task type: classification
Detected 6 numerical features: ['num_age', 'num_fnlwgt', 'num_education-num', 'num_capital-gain', 'num_capital-loss']...
Detected 8 categorical features: ['cat_workclass', 'cat_education', 'cat_marital-status', 'cat_occupation', 'cat_relationship']...

Detected 6 numerical features: ['num_age', 'num_fnlwgt', 'num_education-num', 'num_capital-gain', 'num_capital-loss']...
Detected 8 categorical features: ['cat_workclass', 'cat_education', 'cat_marital-status', 'cat_occupation', 'cat_relationship']...
Detected task type: classification
Detected 6 numerical features: ['num_age', 'num_fnlwgt', 'num_education-num', 'num_capital-gain', 'num_capital-loss']...
Detected 8 categorical features: ['cat_workclass', 'cat_education', 'cat_marital-status', 'cat_occupation', 'cat_relationship']...
Detected task type: classification
Detected 6 numerical features: ['num_age', 'num_fnlwgt', 'num_education-num', 'num_capital-gain', 'num_capital-loss']...
Detected 8 categorical features: ['cat_workclass', 'cat_education', 'cat_marital-status', 'cat_occupation', 'cat_relationship']...
Detected task type: classification
Detected 6 numerical features: ['num_age', 'num_fnlwgt', 'num_education-num', 'num_capital-gain', 'num_capital-loss']...
Detected 8 categorical features: ['cat_workclass', 'cat_education', 'cat_marital-status', 'cat_occupation', 'cat_relationship']...
Detected task type: classification
Detected 6 numerical features: ['num_age', 'num_fnlwgt', 'num_education-num', 'num_capital-gain', 'num_capital-loss']...
Detected 8 categorical features: ['cat_workclass', 'cat_education', 'cat_marital-status', 'cat_occupation', 'cat_relationship']...
Detected task type: classification
Detected 6 numerical features: ['num_age', 'num_fnlwgt', 'num_education-num', 'num_capital-gain', 'num_capital-loss']...
Detected 8 categorical features: ['cat_workclass', 'cat_education', 'cat_marital-status', 'cat_occupation', 'cat_relationship']...
Detected task type: classification
Detected 6 numerical features: ['num_age', 'num_fnlwgt', 'num_education-num', 'num_capital-gain', 'num_capital-loss']...
Detected 8 categorical features: ['cat_workclass', 'cat_education', 'cat_marital-status', 'cat_occupation', 'cat_relationship']...
Detected task type: classification
Detected 6 numerical features: ['num_age', 'num_fnlwgt', 'num_education-num', 'num_capital-gain', 'num_capital-loss']...
Detected 8 categorical features: ['cat_workclass', 'cat_education', 'cat_marital-status', 'cat_occupation', 'cat_relationship']...
Detected task type: classification
Detected 6 numerical features: ['num_age', 'num_fnlwgt', 'num_education-num', 'num_capital-gain', 'num_capital-loss']...
Detected 8 categorical features: ['cat_workclass', 'cat_education', 'cat_marital-status', 'cat_occupation', 'cat_relationship']...

Evaluating wine (classification)...
Detected task type: classification
Detected 13 numerical features: ['num_Alcohol', 'num_Malicacid', 'num_Ash', 'num_Alcalinity_of_ash', 'num_Magnesium']...
Detected 0 categorical features: []
Detected task type: classification
Detected 13 numerical features: ['num_Alcohol', 'num_Malicacid', 'num_Ash', 'num_Alcalinity_of_ash', 'num_Magnesium']...
Detected 0 categorical features: []
Detected task type: classification
Detected 13 numerical features: ['num_Alcohol', 'num_Malicacid', 'num_Ash', 'num_Alcalinity_of_ash', 'num_Magnesium']...
Detected 0 categorical features: []
Detected task type: classification
Detected 13 numerical features: ['num_Alcohol', 'num_Malicacid', 'num_Ash', 'num_Alcalinity_of_ash', 'num_Magnesium']...
Detected 0 categorical features: []
Detected task type: classification
Detected 13 numerical features: ['num_Alcohol', 'num_Malicacid', 'num_Ash', 'num_Alcalinity_of_ash', 'num_Magnesium']...
Detected 0 categorical features: []
Detected task type: classification
Detected 13 numerical features: ['num_Alcohol', 'num_Malicacid', 'num_Ash', 'num_Alcalinity_of_ash', 'num_Magnesium']...
Detected 0 categorical features: []
Detected task type: classification
Detected 13 numerical features: ['num_Alcohol', 'num_Malicacid', 'num_Ash', 'num_Alcalinity_of_ash', 'num_Magnesium']...
Detected 0 categorical features: []
Detected task type: classification
Detected 13 numerical features: ['num_Alcohol', 'num_Malicacid', 'num_Ash', 'num_Alcalinity_of_ash', 'num_Magnesium']...
Detected 0 categorical features: []
Detected task type: classification
Detected 13 numerical features: ['num_Alcohol', 'num_Malicacid', 'num_Ash', 'num_Alcalinity_of_ash', 'num_Magnesium']...
Detected 0 categorical features: []
Detected task type: classification
Detected 13 numerical features: ['num_Alcohol', 'num_Malicacid', 'num_Ash', 'num_Alcalinity_of_ash', 'num_Magnesium']...
Detected 0 categorical features: []
Detected task type: classification
Detected 13 numerical features: ['num_Alcohol', 'num_Malicacid', 'num_Ash', 'num_Alcalinity_of_ash', 'num_Magnesium']...
Detected 0 categorical features: []
Detected task type: classification
Detected 13 numerical features: ['num_Alcohol', 'num_Malicacid', 'num_Ash', 'num_Alcalinity_of_ash', 'num_Magnesium']...
Detected 0 categorical features: []
Detected task type: classification
Detected 13 numerical features: ['num_Alcohol', 'num_Malicacid', 'num_Ash', 'num_Alcalinity_of_ash', 'num_Magnesium']...
Detected 0 categorical features: []
Detected task type: classification
Detected 13 numerical features: ['num_Alcohol', 'num_Malicacid', 'num_Ash', 'num_Alcalinity_of_ash', 'num_Magnesium']...
Detected 0 categorical features: []
Detected task type: classification
Detected 13 numerical features: ['num_Alcohol', 'num_Malicacid', 'num_Ash', 'num_Alcalinity_of_ash', 'num_Magnesium']...
Detected 0 categorical features: []

Evaluating car_evaluation (classification)...

/home/aarchetto/frog-dq/notebooks/../frogdq/preprocessing.py:323: FutureWarning: Downcasting behavior in Series and DataFrame methods 'where', 'mask', and 'clip' is deprecated. In a future version this will not infer object dtypes or cast all-round floats to integers. Instead call result.infer_objects(copy=False) for object inference, or cast round floats explicitly. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X[col] = X[col].clip(lower, upper).infer_objects(copy=False)
/home/aarchetto/frog-dq/notebooks/../frogdq/preprocessing.py:323: FutureWarning: Downcasting behavior in Series and DataFrame methods 'where', 'mask', and 'clip' is deprecated. In a future version this will not infer object dtypes or cast all-round floats to integers. Instead call result.infer_objects(copy=False) for object inference, or cast round floats explicitly. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X[col] = X[col].clip(lower, upper).infer_objects(copy=False)
/home/aarchetto/frog-dq/notebooks/../frogdq/preprocessing.py:323: FutureWarning: Downcasting behavior in Series and DataFrame methods 'where', 'mask', and 'clip' is deprecated. In a future version this will not infer object dtypes or cast all-round floats to integers. Instead call result.infer_objects(copy=False) for object inference, or cast round floats explicitly. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X[col] = X[col].clip(lower, upper).infer_objects(copy=False)
/home/aarchetto/frog-dq/notebooks/../frogdq/preprocessing.py:323: FutureWarning: Downcasting behavior in Series and DataFrame methods 'where', 'mask', and 'clip' is deprecated. In a future version this will not infer object dtypes or cast all-round floats to integers. Instead call result.infer_objects(copy=False) for object inference, or cast round floats explicitly. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X[col] = X[col].clip(lower, upper).infer_objects(copy=False)
/home/aarchetto/frog-dq/notebooks/../frogdq/preprocessing.py:323: FutureWarning: Downcasting behavior in Series and DataFrame methods 'where', 'mask', and 'clip' is deprecated. In a future version this will not infer object dtypes or cast all-round floats to integers. Instead call result.infer_objects(copy=False) for object inference, or cast round floats explicitly. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X[col] = X[col].clip(lower, upper).infer_objects(copy=False)
/home/aarchetto/frog-dq/notebooks/../frogdq/preprocessing.py:323: FutureWarning: Downcasting behavior in Series and DataFrame methods 'where', 'mask', and 'clip' is deprecated. In a future version this will not infer object dtypes or cast all-round floats to integers. Instead call result.infer_objects(copy=False) for object inference, or cast round floats explicitly. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X[col] = X[col].clip(lower, upper).infer_objects(copy=False)
/home/aarchetto/frog-dq/notebooks/../frogdq/preprocessing.py:323: FutureWarning: Downcasting behavior in Series and DataFrame methods 'where', 'mask', and 'clip' is deprecated. In a future version this will not infer object dtypes or cast all-round floats to integers. Instead call result.infer_objects(copy=False) for object inference, or cast round floats explicitly. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X[col] = X[col].clip(lower, upper).infer_objects(copy=False)
/home/aarchetto/frog-dq/notebooks/../frogdq/preprocessing.py:323: FutureWarning: Downcasting behavior in Series and DataFrame methods 'where', 'mask', and 'clip' is deprecated. In a future version this will not infer object dtypes or cast all-round floats to integers. Instead call result.infer_objects(copy=False) for object inference, or cast round floats explicitly. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X[col] = X[col].clip(lower, upper).infer_objects(copy=False)
/home/aarchetto/frog-dq/notebooks/../frogdq/preprocessing.py:323: FutureWarning: Downcasting behavior in Series and DataFrame methods 'where', 'mask', and 'clip' is deprecated. In a future version this will not infer object dtypes or cast all-round floats to integers. Instead call result.infer_objects(copy=False) for object inference, or cast round floats explicitly. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X[col] = X[col].clip(lower, upper).infer_objects(copy=False)
/home/aarchetto/frog-dq/notebooks/../frogdq/preprocessing.py:323: FutureWarning: Downcasting behavior in Series and DataFrame methods 'where', 'mask', and 'clip' is deprecated. In a future version this will not infer object dtypes or cast all-round floats to integers. Instead call result.infer_objects(copy=False) for object inference, or cast round floats explicitly. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X[col] = X[col].clip(lower, upper).infer_objects(copy=False)
/home/aarchetto/frog-dq/notebooks/../frogdq/preprocessing.py:323: FutureWarning: Downcasting behavior in Series and DataFrame methods 'where', 'mask', and 'clip' is deprecated. In a future version this will not infer object dtypes or cast all-round floats to integers. Instead call result.infer_objects(copy=False) for object inference, or cast round floats explicitly. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X[col] = X[col].clip(lower, upper).infer_objects(copy=False)
/home/aarchetto/frog-dq/notebooks/../frogdq/preprocessing.py:323: FutureWarning: Downcasting behavior in Series and DataFrame methods 'where', 'mask', and 'clip' is deprecated. In a future version this will not infer object dtypes or cast all-round floats to integers. Instead call result.infer_objects(copy=False) for object inference, or cast round floats explicitly. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X[col] = X[col].clip(lower, upper).infer_objects(copy=False)
/home/aarchetto/frog-dq/notebooks/../frogdq/preprocessing.py:323: FutureWarning: Downcasting behavior in Series and DataFrame methods 'where', 'mask', and 'clip' is deprecated. In a future version this will not infer object dtypes or cast all-round floats to integers. Instead call result.infer_objects(copy=False) for object inference, or cast round floats explicitly. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X[col] = X[col].clip(lower, upper).infer_objects(copy=False)
/home/aarchetto/frog-dq/notebooks/../frogdq/preprocessing.py:323: FutureWarning: Downcasting behavior in Series and DataFrame methods 'where', 'mask', and 'clip' is deprecated. In a future version this will not infer object dtypes or cast all-round floats to integers. Instead call result.infer_objects(copy=False) for object inference, or cast round floats explicitly. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X[col] = X[col].clip(lower, upper).infer_objects(copy=False)
/home/aarchetto/frog-dq/notebooks/../frogdq/preprocessing.py:323: FutureWarning: Downcasting behavior in Series and DataFrame methods 'where', 'mask', and 'clip' is deprecated. In a future version this will not infer object dtypes or cast all-round floats to integers. Instead call result.infer_objects(copy=False) for object inference, or cast round floats explicitly. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X[col] = X[col].clip(lower, upper).infer_objects(copy=False)
/home/aarchetto/frog-dq/notebooks/../frogdq/preprocessing.py:323: FutureWarning: Downcasting behavior in Series and DataFrame methods 'where', 'mask', and 'clip' is deprecated. In a future version this will not infer object dtypes or cast all-round floats to integers. Instead call result.infer_objects(copy=False) for object inference, or cast round floats explicitly. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X[col] = X[col].clip(lower, upper).infer_objects(copy=False)

Detected task type: classification
Detected 23 numerical features: ['num_X1', 'num_X2', 'num_X3', 'num_X4', 'num_X5']...
Detected 0 categorical features: []

/home/aarchetto/frog-dq/notebooks/../frogdq/preprocessing.py:323: FutureWarning: Downcasting behavior in Series and DataFrame methods 'where', 'mask', and 'clip' is deprecated. In a future version this will not infer object dtypes or cast all-round floats to integers. Instead call result.infer_objects(copy=False) for object inference, or cast round floats explicitly. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X[col] = X[col].clip(lower, upper).infer_objects(copy=False)
/home/aarchetto/frog-dq/notebooks/../frogdq/preprocessing.py:323: FutureWarning: Downcasting behavior in Series and DataFrame methods 'where', 'mask', and 'clip' is deprecated. In a future version this will not infer object dtypes or cast all-round floats to integers. Instead call result.infer_objects(copy=False) for object inference, or cast round floats explicitly. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X[col] = X[col].clip(lower, upper).infer_objects(copy=False)
/home/aarchetto/frog-dq/notebooks/../frogdq/preprocessing.py:323: FutureWarning: Downcasting behavior in Series and DataFrame methods 'where', 'mask', and 'clip' is deprecated. In a future version this will not infer object dtypes or cast all-round floats to integers. Instead call result.infer_objects(copy=False) for object inference, or cast round floats explicitly. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X[col] = X[col].clip(lower, upper).infer_objects(copy=False)
/home/aarchetto/frog-dq/notebooks/../frogdq/preprocessing.py:323: FutureWarning: Downcasting behavior in Series and DataFrame methods 'where', 'mask', and 'clip' is deprecated. In a future version this will not infer object dtypes or cast all-round floats to integers. Instead call result.infer_objects(copy=False) for object inference, or cast round floats explicitly. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X[col] = X[col].clip(lower, upper).infer_objects(copy=False)

Detected task type: classification
Detected 23 numerical features: ['num_X1', 'num_X2', 'num_X3', 'num_X4', 'num_X5']...
Detected 0 categorical features: []
Detected task type: classification
Detected 23 numerical features: ['num_X1', 'num_X2', 'num_X3', 'num_X4', 'num_X5']...
Detected 0 categorical features: []
Detected task type: classification
Detected 23 numerical features: ['num_X1', 'num_X2', 'num_X3', 'num_X4', 'num_X5']...
Detected 0 categorical features: []
Detected task type: classification
Detected 23 numerical features: ['num_X1', 'num_X2', 'num_X3', 'num_X4', 'num_X5']...
Detected 0 categorical features: []
Detected task type: classification
Detected 23 numerical features: ['num_X1', 'num_X2', 'num_X3', 'num_X4', 'num_X5']...
Detected 0 categorical features: []
Detected task type: classification
Detected 23 numerical features: ['num_X1', 'num_X2', 'num_X3', 'num_X4', 'num_X5']...
Detected 0 categorical features: []
Detected task type: classification
Detected 23 numerical features: ['num_X1', 'num_X2', 'num_X3', 'num_X4', 'num_X5']...
Detected 0 categorical features: []
Detected task type: classification
Detected 23 numerical features: ['num_X1', 'num_X2', 'num_X3', 'num_X4', 'num_X5']...
Detected 0 categorical features: []

Evaluating automobile (regression)...
Detected task type: classificationDetected task type: classification
Detected 17 numerical features: ['num_price', 'num_highway-mpg', 'num_city-mpg', 'num_peak-rpm', 'num_horsepower']...
Detected 8 categorical features: ['cat_fuel-system', 'cat_engine-type', 'cat_engine-location', 'cat_drive-wheels', 'cat_body-style']...

Detected 17 numerical features: ['num_price', 'num_highway-mpg', 'num_city-mpg', 'num_peak-rpm', 'num_horsepower']...
Detected task type: classification
Detected 17 numerical features: ['num_price', 'num_highway-mpg', 'num_city-mpg', 'num_peak-rpm', 'num_horsepower']...
Detected 8 categorical features: ['cat_fuel-system', 'cat_engine-type', 'cat_engine-location', 'cat_drive-wheels', 'cat_body-style']...
Detected 8 categorical features: ['cat_fuel-system', 'cat_engine-type', 'cat_engine-location', 'cat_drive-wheels', 'cat_body-style']...
Detected task type: classification
Detected 17 numerical features: ['num_price', 'num_highway-mpg', 'num_city-mpg', 'num_peak-rpm', 'num_horsepower']...
Detected 8 categorical features: ['cat_fuel-system', 'cat_engine-type', 'cat_engine-location', 'cat_drive-wheels', 'cat_body-style']...
Detected task type: classification
Detected 17 numerical features: ['num_price', 'num_highway-mpg', 'num_city-mpg', 'num_peak-rpm', 'num_horsepower']...
Detected 8 categorical features: ['cat_fuel-system', 'cat_engine-type', 'cat_engine-location', 'cat_drive-wheels', 'cat_body-style']...
Detected task type: classification
Detected 17 numerical features: ['num_price', 'num_highway-mpg', 'num_city-mpg', 'num_peak-rpm', 'num_horsepower']...
Detected 8 categorical features: ['cat_fuel-system', 'cat_engine-type', 'cat_engine-location', 'cat_drive-wheels', 'cat_body-style']...
Detected task type: classification
Detected 17 numerical features: ['num_price', 'num_highway-mpg', 'num_city-mpg', 'num_peak-rpm', 'num_horsepower']...
Detected 8 categorical features: ['cat_fuel-system', 'cat_engine-type', 'cat_engine-location', 'cat_drive-wheels', 'cat_body-style']...
Detected task type: classification
Detected 17 numerical features: ['num_price', 'num_highway-mpg', 'num_city-mpg', 'num_peak-rpm', 'num_horsepower']...
Detected 8 categorical features: ['cat_fuel-system', 'cat_engine-type', 'cat_engine-location', 'cat_drive-wheels', 'cat_body-style']...
Detected task type: classification
Detected 17 numerical features: ['num_price', 'num_highway-mpg', 'num_city-mpg', 'num_peak-rpm', 'num_horsepower']...
Detected 8 categorical features: ['cat_fuel-system', 'cat_engine-type', 'cat_engine-location', 'cat_drive-wheels', 'cat_body-style']...
Detected task type: classification
Detected task type: classification
Detected 17 numerical features: ['num_price', 'num_highway-mpg', 'num_city-mpg', 'num_peak-rpm', 'num_horsepower']...
Detected 8 categorical features: ['cat_fuel-system', 'cat_engine-type', 'cat_engine-location', 'cat_drive-wheels', 'cat_body-style']...
Detected 17 numerical features: ['num_price', 'num_highway-mpg', 'num_city-mpg', 'num_peak-rpm', 'num_horsepower']...
Detected 8 categorical features: ['cat_fuel-system', 'cat_engine-type', 'cat_engine-location', 'cat_drive-wheels', 'cat_body-style']...
Detected task type: classification
Detected 17 numerical features: ['num_price', 'num_highway-mpg', 'num_city-mpg', 'num_peak-rpm', 'num_horsepower']...
Detected 8 categorical features: ['cat_fuel-system', 'cat_engine-type', 'cat_engine-location', 'cat_drive-wheels', 'cat_body-style']...
Detected task type: classification
Detected 17 numerical features: ['num_price', 'num_highway-mpg', 'num_city-mpg', 'num_peak-rpm', 'num_horsepower']...
Detected 8 categorical features: ['cat_fuel-system', 'cat_engine-type', 'cat_engine-location', 'cat_drive-wheels', 'cat_body-style']...
Detected task type: classification
Detected 17 numerical features: ['num_price', 'num_highway-mpg', 'num_city-mpg', 'num_peak-rpm', 'num_horsepower']...
Detected 8 categorical features: ['cat_fuel-system', 'cat_engine-type', 'cat_engine-location', 'cat_drive-wheels', 'cat_body-style']...
Detected task type: classification
Detected 17 numerical features: ['num_price', 'num_highway-mpg', 'num_city-mpg', 'num_peak-rpm', 'num_horsepower']...
Detected 8 categorical features: ['cat_fuel-system', 'cat_engine-type', 'cat_engine-location', 'cat_drive-wheels', 'cat_body-style']...

Evaluating mushroom (classification)...
Detected task type: classificationDetected task type: classification

Detected 0 numerical features: []Detected 0 numerical features: []

Detected 22 categorical features: ['cat_cap-shape', 'cat_cap-surface', 'cat_cap-color', 'cat_bruises', 'cat_odor']...Detected 22 categorical features: ['cat_cap-shape', 'cat_cap-surface', 'cat_cap-color', 'cat_bruises', 'cat_odor']...

Detected task type: classification
Detected 0 numerical features: []
Detected 22 categorical features: ['cat_cap-shape', 'cat_cap-surface', 'cat_cap-color', 'cat_bruises', 'cat_odor']...
Detected task type: classification
Detected 0 numerical features: []
Detected 22 categorical features: ['cat_cap-shape', 'cat_cap-surface', 'cat_cap-color', 'cat_bruises', 'cat_odor']...
Detected task type: classification
Detected 0 numerical features: []
Detected 22 categorical features: ['cat_cap-shape', 'cat_cap-surface', 'cat_cap-color', 'cat_bruises', 'cat_odor']...
Detected task type: classification
Detected 0 numerical features: []
Detected 22 categorical features: ['cat_cap-shape', 'cat_cap-surface', 'cat_cap-color', 'cat_bruises', 'cat_odor']...
Detected task type: classification
Detected 0 numerical features: []
Detected 22 categorical features: ['cat_cap-shape', 'cat_cap-surface', 'cat_cap-color', 'cat_bruises', 'cat_odor']...
Detected task type: classification
Detected 0 numerical features: []
Detected 22 categorical features: ['cat_cap-shape', 'cat_cap-surface', 'cat_cap-color', 'cat_bruises', 'cat_odor']...
Detected task type: classification
Detected 0 numerical features: []
Detected 22 categorical features: ['cat_cap-shape', 'cat_cap-surface', 'cat_cap-color', 'cat_bruises', 'cat_odor']...
Detected task type: classification
Detected 0 numerical features: []
Detected 22 categorical features: ['cat_cap-shape', 'cat_cap-surface', 'cat_cap-color', 'cat_bruises', 'cat_odor']...
Detected task type: classification
Detected 0 numerical features: []
Detected 22 categorical features: ['cat_cap-shape', 'cat_cap-surface', 'cat_cap-color', 'cat_bruises', 'cat_odor']...
Detected task type: classification
Detected 0 numerical features: []
Detected 22 categorical features: ['cat_cap-shape', 'cat_cap-surface', 'cat_cap-color', 'cat_bruises', 'cat_odor']...
Detected task type: classification
Detected 0 numerical features: []
Detected 22 categorical features: ['cat_cap-shape', 'cat_cap-surface', 'cat_cap-color', 'cat_bruises', 'cat_odor']...
Detected task type: classification
Detected 0 numerical features: []
Detected 22 categorical features: ['cat_cap-shape', 'cat_cap-surface', 'cat_cap-color', 'cat_bruises', 'cat_odor']...
Detected task type: classification
Detected 0 numerical features: []
Detected 22 categorical features: ['cat_cap-shape', 'cat_cap-surface', 'cat_cap-color', 'cat_bruises', 'cat_odor']...

Evaluating statlog_german_credit_data (classification)...
Detected task type: classification
Detected 7 numerical features: ['num_Attribute2', 'num_Attribute5', 'num_Attribute8', 'num_Attribute11', 'num_Attribute13']...
Detected 13 categorical features: ['cat_Attribute1', 'cat_Attribute3', 'cat_Attribute4', 'cat_Attribute6', 'cat_Attribute7']...
Detected task type: classification
Detected task type: classificationDetected 7 numerical features: ['num_Attribute2', 'num_Attribute5', 'num_Attribute8', 'num_Attribute11', 'num_Attribute13']...
Detected 13 categorical features: ['cat_Attribute1', 'cat_Attribute3', 'cat_Attribute4', 'cat_Attribute6', 'cat_Attribute7']...

Detected 7 numerical features: ['num_Attribute2', 'num_Attribute5', 'num_Attribute8', 'num_Attribute11', 'num_Attribute13']...
Detected 13 categorical features: ['cat_Attribute1', 'cat_Attribute3', 'cat_Attribute4', 'cat_Attribute6', 'cat_Attribute7']...
Detected task type: classification
Detected 7 numerical features: ['num_Attribute2', 'num_Attribute5', 'num_Attribute8', 'num_Attribute11', 'num_Attribute13']...
Detected 13 categorical features: ['cat_Attribute1', 'cat_Attribute3', 'cat_Attribute4', 'cat_Attribute6', 'cat_Attribute7']...
Detected task type: classification
Detected 7 numerical features: ['num_Attribute2', 'num_Attribute5', 'num_Attribute8', 'num_Attribute11', 'num_Attribute13']...
Detected 13 categorical features: ['cat_Attribute1', 'cat_Attribute3', 'cat_Attribute4', 'cat_Attribute6', 'cat_Attribute7']...
Detected task type: classification
Detected 7 numerical features: ['num_Attribute2', 'num_Attribute5', 'num_Attribute8', 'num_Attribute11', 'num_Attribute13']...
Detected 13 categorical features: ['cat_Attribute1', 'cat_Attribute3', 'cat_Attribute4', 'cat_Attribute6', 'cat_Attribute7']...
Detected task type: classification
Detected 7 numerical features: ['num_Attribute2', 'num_Attribute5', 'num_Attribute8', 'num_Attribute11', 'num_Attribute13']...
Detected 13 categorical features: ['cat_Attribute1', 'cat_Attribute3', 'cat_Attribute4', 'cat_Attribute6', 'cat_Attribute7']...
Detected task type: classification
Detected 7 numerical features: ['num_Attribute2', 'num_Attribute5', 'num_Attribute8', 'num_Attribute11', 'num_Attribute13']...
Detected 13 categorical features: ['cat_Attribute1', 'cat_Attribute3', 'cat_Attribute4', 'cat_Attribute6', 'cat_Attribute7']...
Detected task type: classification
Detected 7 numerical features: ['num_Attribute2', 'num_Attribute5', 'num_Attribute8', 'num_Attribute11', 'num_Attribute13']...
Detected 13 categorical features: ['cat_Attribute1', 'cat_Attribute3', 'cat_Attribute4', 'cat_Attribute6', 'cat_Attribute7']...
Detected task type: classification
Detected 7 numerical features: ['num_Attribute2', 'num_Attribute5', 'num_Attribute8', 'num_Attribute11', 'num_Attribute13']...
Detected 13 categorical features: ['cat_Attribute1', 'cat_Attribute3', 'cat_Attribute4', 'cat_Attribute6', 'cat_Attribute7']...
Detected task type: classification
Detected 7 numerical features: ['num_Attribute2', 'num_Attribute5', 'num_Attribute8', 'num_Attribute11', 'num_Attribute13']...
Detected 13 categorical features: ['cat_Attribute1', 'cat_Attribute3', 'cat_Attribute4', 'cat_Attribute6', 'cat_Attribute7']...
Detected task type: classification
Detected 7 numerical features: ['num_Attribute2', 'num_Attribute5', 'num_Attribute8', 'num_Attribute11', 'num_Attribute13']...
Detected 13 categorical features: ['cat_Attribute1', 'cat_Attribute3', 'cat_Attribute4', 'cat_Attribute6', 'cat_Attribute7']...
Detected task type: classification
Detected 7 numerical features: ['num_Attribute2', 'num_Attribute5', 'num_Attribute8', 'num_Attribute11', 'num_Attribute13']...
Detected 13 categorical features: ['cat_Attribute1', 'cat_Attribute3', 'cat_Attribute4', 'cat_Attribute6', 'cat_Attribute7']...
Detected task type: classification
Detected 7 numerical features: ['num_Attribute2', 'num_Attribute5', 'num_Attribute8', 'num_Attribute11', 'num_Attribute13']...
Detected 13 categorical features: ['cat_Attribute1', 'cat_Attribute3', 'cat_Attribute4', 'cat_Attribute6', 'cat_Attribute7']...
Detected task type: classification
Detected 7 numerical features: ['num_Attribute2', 'num_Attribute5', 'num_Attribute8', 'num_Attribute11', 'num_Attribute13']...
Detected 13 categorical features: ['cat_Attribute1', 'cat_Attribute3', 'cat_Attribute4', 'cat_Attribute6', 'cat_Attribute7']...

Evaluating abalone (regression)...
Detected task type: classification
Detected task type: classification
Detected 7 numerical features: ['num_Length', 'num_Diameter', 'num_Height', 'num_Whole_weight', 'num_Shucked_weight']...
Detected 1 categorical features: ['cat_Sex']
Detected 7 numerical features: ['num_Length', 'num_Diameter', 'num_Height', 'num_Whole_weight', 'num_Shucked_weight']...
Detected 1 categorical features: ['cat_Sex']
Detected task type: classification
Detected task type: classification
Detected 7 numerical features: ['num_Length', 'num_Diameter', 'num_Height', 'num_Whole_weight', 'num_Shucked_weight']...Detected 7 numerical features: ['num_Length', 'num_Diameter', 'num_Height', 'num_Whole_weight', 'num_Shucked_weight']...
Detected 1 categorical features: ['cat_Sex']

Detected 1 categorical features: ['cat_Sex']
Detected task type: classification
Detected 7 numerical features: ['num_Length', 'num_Diameter', 'num_Height', 'num_Whole_weight', 'num_Shucked_weight']...
Detected 1 categorical features: ['cat_Sex']
Detected task type: classification
Detected 7 numerical features: ['num_Length', 'num_Diameter', 'num_Height', 'num_Whole_weight', 'num_Shucked_weight']...
Detected 1 categorical features: ['cat_Sex']
Detected task type: classification
Detected 7 numerical features: ['num_Length', 'num_Diameter', 'num_Height', 'num_Whole_weight', 'num_Shucked_weight']...
Detected 1 categorical features: ['cat_Sex']
Detected task type: classification
Detected 7 numerical features: ['num_Length', 'num_Diameter', 'num_Height', 'num_Whole_weight', 'num_Shucked_weight']...
Detected 1 categorical features: ['cat_Sex']
Detected task type: classification
Detected 7 numerical features: ['num_Length', 'num_Diameter', 'num_Height', 'num_Whole_weight', 'num_Shucked_weight']...
Detected 1 categorical features: ['cat_Sex']
Detected task type: classification
Detected 7 numerical features: ['num_Length', 'num_Diameter', 'num_Height', 'num_Whole_weight', 'num_Shucked_weight']...
Detected 1 categorical features: ['cat_Sex']
Detected task type: classification
Detected 7 numerical features: ['num_Length', 'num_Diameter', 'num_Height', 'num_Whole_weight', 'num_Shucked_weight']...
Detected 1 categorical features: ['cat_Sex']
Detected task type: classification
Detected 7 numerical features: ['num_Length', 'num_Diameter', 'num_Height', 'num_Whole_weight', 'num_Shucked_weight']...
Detected 1 categorical features: ['cat_Sex']
Detected task type: classification
Detected 7 numerical features: ['num_Length', 'num_Diameter', 'num_Height', 'num_Whole_weight', 'num_Shucked_weight']...
Detected 1 categorical features: ['cat_Sex']
Detected task type: classification
Detected 7 numerical features: ['num_Length', 'num_Diameter', 'num_Height', 'num_Whole_weight', 'num_Shucked_weight']...
Detected 1 categorical features: ['cat_Sex']
Detected task type: classification
Detected 7 numerical features: ['num_Length', 'num_Diameter', 'num_Height', 'num_Whole_weight', 'num_Shucked_weight']...
Detected 1 categorical features: ['cat_Sex']

Evaluating bike_sharing (regression)...
Detected task type: regressionDetected task type: regression
Detected 4 numerical features: ['num_temp', 'num_atemp', 'num_hum', 'num_windspeed']
Detected 8 categorical features: ['cat_season', 'cat_yr', 'cat_mnth', 'cat_hr', 'cat_holiday']...

Detected 1 date features: ['dat_dteday']Detected 4 numerical features: ['num_temp', 'num_atemp', 'num_hum', 'num_windspeed']

Detected 8 categorical features: ['cat_season', 'cat_yr', 'cat_mnth', 'cat_hr', 'cat_holiday']...
Detected 1 date features: ['dat_dteday']
Detected task type: regression
Detected 4 numerical features: ['num_temp', 'num_atemp', 'num_hum', 'num_windspeed']
Detected 8 categorical features: ['cat_season', 'cat_yr', 'cat_mnth', 'cat_hr', 'cat_holiday']...
Detected 1 date features: ['dat_dteday']
Detected task type: regression
Detected 4 numerical features: ['num_temp', 'num_atemp', 'num_hum', 'num_windspeed']
Detected 8 categorical features: ['cat_season', 'cat_yr', 'cat_mnth', 'cat_hr', 'cat_holiday']...
Detected 1 date features: ['dat_dteday']
Detected task type: regression
Detected 4 numerical features: ['num_temp', 'num_atemp', 'num_hum', 'num_windspeed']
Detected 8 categorical features: ['cat_season', 'cat_yr', 'cat_mnth', 'cat_hr', 'cat_holiday']...
Detected 1 date features: ['dat_dteday']
Detected task type: regression
Detected 4 numerical features: ['num_temp', 'num_atemp', 'num_hum', 'num_windspeed']
Detected 8 categorical features: ['cat_season', 'cat_yr', 'cat_mnth', 'cat_hr', 'cat_holiday']...
Detected 1 date features: ['dat_dteday']
Detected task type: regression
Detected 4 numerical features: ['num_temp', 'num_atemp', 'num_hum', 'num_windspeed']
Detected 8 categorical features: ['cat_season', 'cat_yr', 'cat_mnth', 'cat_hr', 'cat_holiday']...
Detected 1 date features: ['dat_dteday']
Detected task type: regression
Detected 4 numerical features: ['num_temp', 'num_atemp', 'num_hum', 'num_windspeed']
Detected 8 categorical features: ['cat_season', 'cat_yr', 'cat_mnth', 'cat_hr', 'cat_holiday']...
Detected 1 date features: ['dat_dteday']
Detected task type: regression
Detected 4 numerical features: ['num_temp', 'num_atemp', 'num_hum', 'num_windspeed']
Detected 8 categorical features: ['cat_season', 'cat_yr', 'cat_mnth', 'cat_hr', 'cat_holiday']...
Detected 1 date features: ['dat_dteday']
Detected task type: regression
Detected 4 numerical features: ['num_temp', 'num_atemp', 'num_hum', 'num_windspeed']
Detected 8 categorical features: ['cat_season', 'cat_yr', 'cat_mnth', 'cat_hr', 'cat_holiday']...
Detected 1 date features: ['dat_dteday']
Detected task type: regression
Detected 4 numerical features: ['num_temp', 'num_atemp', 'num_hum', 'num_windspeed']
Detected 8 categorical features: ['cat_season', 'cat_yr', 'cat_mnth', 'cat_hr', 'cat_holiday']...
Detected 1 date features: ['dat_dteday']
Detected task type: regression
Detected 4 numerical features: ['num_temp', 'num_atemp', 'num_hum', 'num_windspeed']
Detected 8 categorical features: ['cat_season', 'cat_yr', 'cat_mnth', 'cat_hr', 'cat_holiday']...
Detected 1 date features: ['dat_dteday']
Detected task type: regression
Detected 4 numerical features: ['num_temp', 'num_atemp', 'num_hum', 'num_windspeed']
Detected 8 categorical features: ['cat_season', 'cat_yr', 'cat_mnth', 'cat_hr', 'cat_holiday']...
Detected 1 date features: ['dat_dteday']
Detected task type: regression
Detected 4 numerical features: ['num_temp', 'num_atemp', 'num_hum', 'num_windspeed']
Detected 8 categorical features: ['cat_season', 'cat_yr', 'cat_mnth', 'cat_hr', 'cat_holiday']...
Detected 1 date features: ['dat_dteday']
Detected task type: regression
Detected 4 numerical features: ['num_temp', 'num_atemp', 'num_hum', 'num_windspeed']
Detected 8 categorical features: ['cat_season', 'cat_yr', 'cat_mnth', 'cat_hr', 'cat_holiday']...
Detected 1 date features: ['dat_dteday']

Evaluating estimation_of_obesity_levels_based_on_eating_habits_and_physical_condition (classification)...
Detected task type: classificationDetected task type: classification

/home/aarchetto/frog-dq/notebooks/../frogdq/preprocessing.py:323: FutureWarning: Downcasting behavior in Series and DataFrame methods 'where', 'mask', and 'clip' is deprecated. In a future version this will not infer object dtypes or cast all-round floats to integers. Instead call result.infer_objects(copy=False) for object inference, or cast round floats explicitly. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X[col] = X[col].clip(lower, upper).infer_objects(copy=False)
/home/aarchetto/frog-dq/notebooks/../frogdq/preprocessing.py:323: FutureWarning: Downcasting behavior in Series and DataFrame methods 'where', 'mask', and 'clip' is deprecated. In a future version this will not infer object dtypes or cast all-round floats to integers. Instead call result.infer_objects(copy=False) for object inference, or cast round floats explicitly. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X[col] = X[col].clip(lower, upper).infer_objects(copy=False)

Detected task type: classification
Detected 6 numerical features: ['num_A15', 'num_A14', 'num_A11', 'num_A8', 'num_A3']...
Detected 9 categorical features: ['cat_A13', 'cat_A12', 'cat_A10', 'cat_A9', 'cat_A7']...
Detected task type: classification
Detected 6 numerical features: ['num_A15', 'num_A14', 'num_A11', 'num_A8', 'num_A3']...
Detected 9 categorical features: ['cat_A13', 'cat_A12', 'cat_A10', 'cat_A9', 'cat_A7']...
Detected task type: classification
Detected 6 numerical features: ['num_A15', 'num_A14', 'num_A11', 'num_A8', 'num_A3']...
Detected 9 categorical features: ['cat_A13', 'cat_A12', 'cat_A10', 'cat_A9', 'cat_A7']...
Detected task type: classification
Detected 6 numerical features: ['num_A15', 'num_A14', 'num_A11', 'num_A8', 'num_A3']...
Detected 9 categorical features: ['cat_A13', 'cat_A12', 'cat_A10', 'cat_A9', 'cat_A7']...
Detected task type: classification
Detected 6 numerical features: ['num_A15', 'num_A14', 'num_A11', 'num_A8', 'num_A3']...
Detected 9 categorical features: ['cat_A13', 'cat_A12', 'cat_A10', 'cat_A9', 'cat_A7']...
Detected task type: classification
Detected 6 numerical features: ['num_A15', 'num_A14', 'num_A11', 'num_A8', 'num_A3']...
Detected 9 categorical features: ['cat_A13', 'cat_A12', 'cat_A10', 'cat_A9', 'cat_A7']...
Detected task type: classification
Detected 6 numerical features: ['num_A15', 'num_A14', 'num_A11', 'num_A8', 'num_A3']...
Detected 9 categorical features: ['cat_A13', 'cat_A12', 'cat_A10', 'cat_A9', 'cat_A7']...
Detected task type: classification
Detected 6 numerical features: ['num_A15', 'num_A14', 'num_A11', 'num_A8', 'num_A3']...
Detected 9 categorical features: ['cat_A13', 'cat_A12', 'cat_A10', 'cat_A9', 'cat_A7']...

/home/aarchetto/frog-dq/notebooks/../frogdq/preprocessing.py:323: FutureWarning: Downcasting behavior in Series and DataFrame methods 'where', 'mask', and 'clip' is deprecated. In a future version this will not infer object dtypes or cast all-round floats to integers. Instead call result.infer_objects(copy=False) for object inference, or cast round floats explicitly. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X[col] = X[col].clip(lower, upper).infer_objects(copy=False)
/home/aarchetto/frog-dq/notebooks/../frogdq/preprocessing.py:323: FutureWarning: Downcasting behavior in Series and DataFrame methods 'where', 'mask', and 'clip' is deprecated. In a future version this will not infer object dtypes or cast all-round floats to integers. Instead call result.infer_objects(copy=False) for object inference, or cast round floats explicitly. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X[col] = X[col].clip(lower, upper).infer_objects(copy=False)
/home/aarchetto/frog-dq/notebooks/../frogdq/preprocessing.py:323: FutureWarning: Downcasting behavior in Series and DataFrame methods 'where', 'mask', and 'clip' is deprecated. In a future version this will not infer object dtypes or cast all-round floats to integers. Instead call result.infer_objects(copy=False) for object inference, or cast round floats explicitly. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X[col] = X[col].clip(lower, upper).infer_objects(copy=False)
/home/aarchetto/frog-dq/notebooks/../frogdq/preprocessing.py:323: FutureWarning: Downcasting behavior in Series and DataFrame methods 'where', 'mask', and 'clip' is deprecated. In a future version this will not infer object dtypes or cast all-round floats to integers. Instead call result.infer_objects(copy=False) for object inference, or cast round floats explicitly. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X[col] = X[col].clip(lower, upper).infer_objects(copy=False)

Evaluating real_estate_valuation (regression)...
Detected task type: regression
Detected 6 numerical features: ['num_X1 transaction date', 'num_X2 house age', 'num_X3 distance to the nearest MRT station', 'num_X4 number of convenience stores', 'num_X5 latitude']...
Detected 0 categorical features: []
Detected task type: regression
Detected 6 numerical features: ['num_X1 transaction date', 'num_X2 house age', 'num_X3 distance to the nearest MRT station', 'num_X4 number of convenience stores', 'num_X5 latitude']...
Detected 0 categorical features: []
Detected task type: regression
Detected 6 numerical features: ['num_X1 transaction date', 'num_X2 house age', 'num_X3 distance to the nearest MRT station', 'num_X4 number of convenience stores', 'num_X5 latitude']...
Detected 0 categorical features: []
Detected task type: regression
Detected 6 numerical features: ['num_X1 transaction date', 'num_X2 house age', 'num_X3 distance to the nearest MRT station', 'num_X4 number of convenience stores', 'num_X5 latitude']...
Detected 0 categorical features: []
Detected task type: regression
Detected 6 numerical features: ['num_X1 transaction date', 'num_X2 house age', 'num_X3 distance to the nearest MRT station', 'num_X4 number of convenience stores', 'num_X5 latitude']...
Detected 0 categorical features: []
Detected task type: regression
Detected 6 numerical features: ['num_X1 transaction date', 'num_X2 house age', 'num_X3 distance to the nearest MRT station', 'num_X4 number of convenience stores', 'num_X5 latitude']...
Detected 0 categorical features: []
Detected task type: regression
Detected 6 numerical features: ['num_X1 transaction date', 'num_X2 house age', 'num_X3 distance to the nearest MRT station', 'num_X4 number of convenience stores', 'num_X5 latitude']...
Detected 0 categorical features: []
Detected task type: regression
Detected 6 numerical features: ['num_X1 transaction date', 'num_X2 house age', 'num_X3 distance to the nearest MRT station', 'num_X4 number of convenience stores', 'num_X5 latitude']...
Detected 0 categorical features: []
Detected task type: regression
Detected 6 numerical features: ['num_X1 transaction date', 'num_X2 house age', 'num_X3 distance to the nearest MRT station', 'num_X4 number of convenience stores', 'num_X5 latitude']...
Detected 0 categorical features: []
Detected task type: regression
Detected 6 numerical features: ['num_X1 transaction date', 'num_X2 house age', 'num_X3 distance to the nearest MRT station', 'num_X4 number of convenience stores', 'num_X5 latitude']...
Detected 0 categorical features: []
Detected task type: regression
Detected 6 numerical features: ['num_X1 transaction date', 'num_X2 house age', 'num_X3 distance to the nearest MRT station', 'num_X4 number of convenience stores', 'num_X5 latitude']...
Detected 0 categorical features: []
Detected task type: regression
Detected 6 numerical features: ['num_X1 transaction date', 'num_X2 house age', 'num_X3 distance to the nearest MRT station', 'num_X4 number of convenience stores', 'num_X5 latitude']...
Detected 0 categorical features: []
Detected task type: regression
Detected 6 numerical features: ['num_X1 transaction date', 'num_X2 house age', 'num_X3 distance to the nearest MRT station', 'num_X4 number of convenience stores', 'num_X5 latitude']...
Detected 0 categorical features: []
Detected task type: regression
Detected 6 numerical features: ['num_X1 transaction date', 'num_X2 house age', 'num_X3 distance to the nearest MRT station', 'num_X4 number of convenience stores', 'num_X5 latitude']...
Detected 0 categorical features: []
Detected task type: regression
Detected 6 numerical features: ['num_X1 transaction date', 'num_X2 house age', 'num_X3 distance to the nearest MRT station', 'num_X4 number of convenience stores', 'num_X5 latitude']...
Detected 0 categorical features: []

Evaluating chronic_kidney_disease (classification)...
Detected task type: classification
Detected 11 numerical features: ['num_age', 'num_bp', 'num_bgr', 'num_bu', 'num_sc']...
Detected 13 categorical features: ['cat_sg', 'cat_al', 'cat_su', 'cat_rbc', 'cat_pc']...
Detected task type: classification
Detected task type: classification
Detected 11 numerical features: ['num_age', 'num_bp', 'num_bgr', 'num_bu', 'num_sc']...
Detected 13 categorical features: ['cat_sg', 'cat_al', 'cat_su', 'cat_rbc', 'cat_pc']...
Detected 11 numerical features: ['num_age', 'num_bp', 'num_bgr', 'num_bu', 'num_sc']...
Detected 13 categorical features: ['cat_sg', 'cat_al', 'cat_su', 'cat_rbc', 'cat_pc']...Detected task type: classification

Detected 11 numerical features: ['num_age', 'num_bp', 'num_bgr', 'num_bu', 'num_sc']...
Detected 13 categorical features: ['cat_sg', 'cat_al', 'cat_su', 'cat_rbc', 'cat_pc']...
Detected task type: classification
Detected 11 numerical features: ['num_age', 'num_bp', 'num_bgr', 'num_bu', 'num_sc']...
Detected 13 categorical features: ['cat_sg', 'cat_al', 'cat_su', 'cat_rbc', 'cat_pc']...
Detected task type: classification
Detected 11 numerical features: ['num_age', 'num_bp', 'num_bgr', 'num_bu', 'num_sc']...
Detected 13 categorical features: ['cat_sg', 'cat_al', 'cat_su', 'cat_rbc', 'cat_pc']...
Detected task type: classification
Detected 11 numerical features: ['num_age', 'num_bp', 'num_bgr', 'num_bu', 'num_sc']...
Detected 13 categorical features: ['cat_sg', 'cat_al', 'cat_su', 'cat_rbc', 'cat_pc']...
Detected task type: classification
Detected 11 numerical features: ['num_age', 'num_bp', 'num_bgr', 'num_bu', 'num_sc']...
Detected 13 categorical features: ['cat_sg', 'cat_al', 'cat_su', 'cat_rbc', 'cat_pc']...
Detected task type: classification
Detected 11 numerical features: ['num_age', 'num_bp', 'num_bgr', 'num_bu', 'num_sc']...
Detected 13 categorical features: ['cat_sg', 'cat_al', 'cat_su', 'cat_rbc', 'cat_pc']...
Detected task type: classification
Detected 11 numerical features: ['num_age', 'num_bp', 'num_bgr', 'num_bu', 'num_sc']...
Detected 13 categorical features: ['cat_sg', 'cat_al', 'cat_su', 'cat_rbc', 'cat_pc']...
Detected task type: classification
Detected 11 numerical features: ['num_age', 'num_bp', 'num_bgr', 'num_bu', 'num_sc']...
Detected 13 categorical features: ['cat_sg', 'cat_al', 'cat_su', 'cat_rbc', 'cat_pc']...
Detected task type: classification
Detected 11 numerical features: ['num_age', 'num_bp', 'num_bgr', 'num_bu', 'num_sc']...
Detected 13 categorical features: ['cat_sg', 'cat_al', 'cat_su', 'cat_rbc', 'cat_pc']...
Detected task type: classification
Detected 11 numerical features: ['num_age', 'num_bp', 'num_bgr', 'num_bu', 'num_sc']...
Detected 13 categorical features: ['cat_sg', 'cat_al', 'cat_su', 'cat_rbc', 'cat_pc']...
Detected task type: classification
Detected 11 numerical features: ['num_age', 'num_bp', 'num_bgr', 'num_bu', 'num_sc']...
Detected 13 categorical features: ['cat_sg', 'cat_al', 'cat_su', 'cat_rbc', 'cat_pc']...
Detected task type: classification
Detected 11 numerical features: ['num_age', 'num_bp', 'num_bgr', 'num_bu', 'num_sc']...
Detected 13 categorical features: ['cat_sg', 'cat_al', 'cat_su', 'cat_rbc', 'cat_pc']...

Evaluating concrete_compressive_strength (regression)...
Detected task type: regression
Detected 8 numerical features: ['num_Cement', 'num_Blast Furnace Slag', 'num_Fly Ash', 'num_Water', 'num_Superplasticizer']...
Detected 0 categorical features: []
Detected task type: regression
Detected 8 numerical features: ['num_Cement', 'num_Blast Furnace Slag', 'num_Fly Ash', 'num_Water', 'num_Superplasticizer']...
Detected 0 categorical features: []
Detected task type: regression
Detected 8 numerical features: ['num_Cement', 'num_Blast Furnace Slag', 'num_Fly Ash', 'num_Water', 'num_Superplasticizer']...
Detected 0 categorical features: []Detected task type: regression

Detected 8 numerical features: ['num_Cement', 'num_Blast Furnace Slag', 'num_Fly Ash', 'num_Water', 'num_Superplasticizer']...
Detected 0 categorical features: []
Detected task type: regression
Detected 8 numerical features: ['num_Cement', 'num_Blast Furnace Slag', 'num_Fly Ash', 'num_Water', 'num_Superplasticizer']...
Detected 0 categorical features: []
Detected task type: regression
Detected 8 numerical features: ['num_Cement', 'num_Blast Furnace Slag', 'num_Fly Ash', 'num_Water', 'num_Superplasticizer']...
Detected 0 categorical features: []
Detected task type: regression
Detected 8 numerical features: ['num_Cement', 'num_Blast Furnace Slag', 'num_Fly Ash', 'num_Water', 'num_Superplasticizer']...
Detected 0 categorical features: []
Detected task type: regression
Detected 8 numerical features: ['num_Cement', 'num_Blast Furnace Slag', 'num_Fly Ash', 'num_Water', 'num_Superplasticizer']...
Detected 0 categorical features: []
Detected task type: regression
Detected 8 numerical features: ['num_Cement', 'num_Blast Furnace Slag', 'num_Fly Ash', 'num_Water', 'num_Superplasticizer']...
Detected 0 categorical features: []
Detected task type: regression
Detected 8 numerical features: ['num_Cement', 'num_Blast Furnace Slag', 'num_Fly Ash', 'num_Water', 'num_Superplasticizer']...
Detected 0 categorical features: []
Detected task type: regression
Detected 8 numerical features: ['num_Cement', 'num_Blast Furnace Slag', 'num_Fly Ash', 'num_Water', 'num_Superplasticizer']...
Detected 0 categorical features: []
Detected task type: regression
Detected 8 numerical features: ['num_Cement', 'num_Blast Furnace Slag', 'num_Fly Ash', 'num_Water', 'num_Superplasticizer']...
Detected 0 categorical features: []
Detected task type: regression
Detected 8 numerical features: ['num_Cement', 'num_Blast Furnace Slag', 'num_Fly Ash', 'num_Water', 'num_Superplasticizer']...
Detected 0 categorical features: []
Detected task type: regression
Detected 8 numerical features: ['num_Cement', 'num_Blast Furnace Slag', 'num_Fly Ash', 'num_Water', 'num_Superplasticizer']...
Detected 0 categorical features: []
Detected task type: regression
Detected 8 numerical features: ['num_Cement', 'num_Blast Furnace Slag', 'num_Fly Ash', 'num_Water', 'num_Superplasticizer']...
Detected 0 categorical features: []

Evaluating wholesale_customers (classification)...
Detected task type: classificationDetected task type: classification
Detected 6 numerical features: ['num_Fresh', 'num_Milk', 'num_Grocery', 'num_Frozen', 'num_Detergents_Paper']...
Detected 1 categorical features: ['cat_Channel']

Detected 6 numerical features: ['num_Fresh', 'num_Milk', 'num_Grocery', 'num_Frozen', 'num_Detergents_Paper']...
Detected 1 categorical features: ['cat_Channel']
Detected task type: classification
Detected 6 numerical features: ['num_Fresh', 'num_Milk', 'num_Grocery', 'num_Frozen', 'num_Detergents_Paper']...
Detected 1 categorical features: ['cat_Channel']
Detected task type: classification
Detected 6 numerical features: ['num_Fresh', 'num_Milk', 'num_Grocery', 'num_Frozen', 'num_Detergents_Paper']...
Detected 1 categorical features: ['cat_Channel']
Detected task type: classification
Detected 6 numerical features: ['num_Fresh', 'num_Milk', 'num_Grocery', 'num_Frozen', 'num_Detergents_Paper']...
Detected 1 categorical features: ['cat_Channel']
Detected task type: classification
Detected 6 numerical features: ['num_Fresh', 'num_Milk', 'num_Grocery', 'num_Frozen', 'num_Detergents_Paper']...
Detected 1 categorical features: ['cat_Channel']
Detected task type: classification
Detected 6 numerical features: ['num_Fresh', 'num_Milk', 'num_Grocery', 'num_Frozen', 'num_Detergents_Paper']...
Detected 1 categorical features: ['cat_Channel']
Detected task type: classification
Detected 6 numerical features: ['num_Fresh', 'num_Milk', 'num_Grocery', 'num_Frozen', 'num_Detergents_Paper']...
Detected 1 categorical features: ['cat_Channel']
Detected task type: classification
Detected 6 numerical features: ['num_Fresh', 'num_Milk', 'num_Grocery', 'num_Frozen', 'num_Detergents_Paper']...
Detected 1 categorical features: ['cat_Channel']
Detected task type: classification
Detected 6 numerical features: ['num_Fresh', 'num_Milk', 'num_Grocery', 'num_Frozen', 'num_Detergents_Paper']...
Detected 1 categorical features: ['cat_Channel']
Detected task type: classification
Detected 6 numerical features: ['num_Fresh', 'num_Milk', 'num_Grocery', 'num_Frozen', 'num_Detergents_Paper']...
Detected 1 categorical features: ['cat_Channel']
Detected task type: classification
Detected 6 numerical features: ['num_Fresh', 'num_Milk', 'num_Grocery', 'num_Frozen', 'num_Detergents_Paper']...
Detected 1 categorical features: ['cat_Channel']
Detected task type: classification
Detected 6 numerical features: ['num_Fresh', 'num_Milk', 'num_Grocery', 'num_Frozen', 'num_Detergents_Paper']...
Detected 1 categorical features: ['cat_Channel']
Detected task type: classification
Detected 6 numerical features: ['num_Fresh', 'num_Milk', 'num_Grocery', 'num_Frozen', 'num_Detergents_Paper']...
Detected 1 categorical features: ['cat_Channel']

/home/aarchetto/frog-dq/notebooks/../frogdq/preprocessing.py:323: FutureWarning: Downcasting behavior in Series and DataFrame methods 'where', 'mask', and 'clip' is deprecated. In a future version this will not infer object dtypes or cast all-round floats to integers. Instead call result.infer_objects(copy=False) for object inference, or cast round floats explicitly. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X[col] = X[col].clip(lower, upper).infer_objects(copy=False)
/home/aarchetto/frog-dq/notebooks/../frogdq/preprocessing.py:323: FutureWarning: Downcasting behavior in Series and DataFrame methods 'where', 'mask', and 'clip' is deprecated. In a future version this will not infer object dtypes or cast all-round floats to integers. Instead call result.infer_objects(copy=False) for object inference, or cast round floats explicitly. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X[col] = X[col].clip(lower, upper).infer_objects(copy=False)

Detected task type: classification
Detected 6 numerical features: ['num_Fresh', 'num_Milk', 'num_Grocery', 'num_Frozen', 'num_Detergents_Paper']...
Detected 1 categorical features: ['cat_Channel']

Evaluating parkinsons (regression)...
Detected task type: classification
Detected 22 numerical features: ['num_MDVP:Fo', 'num_MDVP:Fhi', 'num_MDVP:Flo', 'num_MDVP:Jitter', 'num_MDVP:Jitter.1']...
Detected 0 categorical features: []
Detected task type: classification
Detected 22 numerical features: ['num_MDVP:Fo', 'num_MDVP:Fhi', 'num_MDVP:Flo', 'num_MDVP:Jitter', 'num_MDVP:Jitter.1']...
Detected 0 categorical features: []
Detected task type: classification
Detected 22 numerical features: ['num_MDVP:Fo', 'num_MDVP:Fhi', 'num_MDVP:Flo', 'num_MDVP:Jitter', 'num_MDVP:Jitter.1']...
Detected 0 categorical features: []
Detected task type: classification
Detected 22 numerical features: ['num_MDVP:Fo', 'num_MDVP:Fhi', 'num_MDVP:Flo', 'num_MDVP:Jitter', 'num_MDVP:Jitter.1']...
Detected 0 categorical features: []
Detected task type: classification
Detected 22 numerical features: ['num_MDVP:Fo', 'num_MDVP:Fhi', 'num_MDVP:Flo', 'num_MDVP:Jitter', 'num_MDVP:Jitter.1']...
Detected 0 categorical features: []
Detected task type: classification
Detected 22 numerical features: ['num_MDVP:Fo', 'num_MDVP:Fhi', 'num_MDVP:Flo', 'num_MDVP:Jitter', 'num_MDVP:Jitter.1']...
Detected 0 categorical features: []
Detected task type: classification
Detected 22 numerical features: ['num_MDVP:Fo', 'num_MDVP:Fhi', 'num_MDVP:Flo', 'num_MDVP:Jitter', 'num_MDVP:Jitter.1']...
Detected 0 categorical features: []
Detected task type: classification
Detected 22 numerical features: ['num_MDVP:Fo', 'num_MDVP:Fhi', 'num_MDVP:Flo', 'num_MDVP:Jitter', 'num_MDVP:Jitter.1']...
Detected 0 categorical features: []
Detected task type: classification
Detected 22 numerical features: ['num_MDVP:Fo', 'num_MDVP:Fhi', 'num_MDVP:Flo', 'num_MDVP:Jitter', 'num_MDVP:Jitter.1']...
Detected 0 categorical features: []
Detected task type: classification
Detected 22 numerical features: ['num_MDVP:Fo', 'num_MDVP:Fhi', 'num_MDVP:Flo', 'num_MDVP:Jitter', 'num_MDVP:Jitter.1']...
Detected 0 categorical features: []
Detected task type: classification
Detected 22 numerical features: ['num_MDVP:Fo', 'num_MDVP:Fhi', 'num_MDVP:Flo', 'num_MDVP:Jitter', 'num_MDVP:Jitter.1']...
Detected 0 categorical features: []
Detected task type: classification
Detected 22 numerical features: ['num_MDVP:Fo', 'num_MDVP:Fhi', 'num_MDVP:Flo', 'num_MDVP:Jitter', 'num_MDVP:Jitter.1']...
Detected 0 categorical features: []
Detected task type: classification
Detected 22 numerical features: ['num_MDVP:Fo', 'num_MDVP:Fhi', 'num_MDVP:Flo', 'num_MDVP:Jitter', 'num_MDVP:Jitter.1']...
Detected 0 categorical features: []
Detected task type: classification
Detected 22 numerical features: ['num_MDVP:Fo', 'num_MDVP:Fhi', 'num_MDVP:Flo', 'num_MDVP:Jitter', 'num_MDVP:Jitter.1']...
Detected 0 categorical features: []
Detected task type: classification
Detected 22 numerical features: ['num_MDVP:Fo', 'num_MDVP:Fhi', 'num_MDVP:Flo', 'num_MDVP:Jitter', 'num_MDVP:Jitter.1']...
Detected 0 categorical features: []

Evaluating seoul_bike_sharing_demand (classification)...
Detected task type: classification
Detected 10 numerical features: ['num_Rented Bike Count', 'num_Hour', 'num_Temperature', 'num_Humidity', 'num_Wind speed']...
Detected 2 categorical features: ['cat_Seasons', 'cat_Holiday']
Detected 1 date features: ['dat_Date']
Detected task type: classification
Detected 10 numerical features: ['num_Rented Bike Count', 'num_Hour', 'num_Temperature', 'num_Humidity', 'num_Wind speed']...
Detected 2 categorical features: ['cat_Seasons', 'cat_Holiday']
Detected 1 date features: ['dat_Date']
Detected task type: classification
Detected 10 numerical features: ['num_Rented Bike Count', 'num_Hour', 'num_Temperature', 'num_Humidity', 'num_Wind speed']...
Detected 2 categorical features: ['cat_Seasons', 'cat_Holiday']
Detected 1 date features: ['dat_Date']
Detected task type: classification
Detected 10 numerical features: ['num_Rented Bike Count', 'num_Hour', 'num_Temperature', 'num_Humidity', 'num_Wind speed']...Detected task type: classification

Detected 10 numerical features: ['num_Rented Bike Count', 'num_Hour', 'num_Temperature', 'num_Humidity', 'num_Wind speed']...
Detected 2 categorical features: ['cat_Seasons', 'cat_Holiday']
Detected 1 date features: ['dat_Date']
Detected 2 categorical features: ['cat_Seasons', 'cat_Holiday']
Detected 1 date features: ['dat_Date']
Detected task type: classification
Detected 10 numerical features: ['num_Rented Bike Count', 'num_Hour', 'num_Temperature', 'num_Humidity', 'num_Wind speed']...
Detected 2 categorical features: ['cat_Seasons', 'cat_Holiday']
Detected 1 date features: ['dat_Date']
Detected task type: classification
Detected 10 numerical features: ['num_Rented Bike Count', 'num_Hour', 'num_Temperature', 'num_Humidity', 'num_Wind speed']...
Detected 2 categorical features: ['cat_Seasons', 'cat_Holiday']
Detected 1 date features: ['dat_Date']
Detected task type: classification
Detected 10 numerical features: ['num_Rented Bike Count', 'num_Hour', 'num_Temperature', 'num_Humidity', 'num_Wind speed']...
Detected 2 categorical features: ['cat_Seasons', 'cat_Holiday']
Detected 1 date features: ['dat_Date']
Detected task type: classification
Detected 10 numerical features: ['num_Rented Bike Count', 'num_Hour', 'num_Temperature', 'num_Humidity', 'num_Wind speed']...
Detected 2 categorical features: ['cat_Seasons', 'cat_Holiday']
Detected 1 date features: ['dat_Date']
Detected task type: classification
Detected 10 numerical features: ['num_Rented Bike Count', 'num_Hour', 'num_Temperature', 'num_Humidity', 'num_Wind speed']...
Detected 2 categorical features: ['cat_Seasons', 'cat_Holiday']
Detected 1 date features: ['dat_Date']
Detected task type: classification
Detected 10 numerical features: ['num_Rented Bike Count', 'num_Hour', 'num_Temperature', 'num_Humidity', 'num_Wind speed']...
Detected task type: classification
Detected 10 numerical features: ['num_Rented Bike Count', 'num_Hour', 'num_Temperature', 'num_Humidity', 'num_Wind speed']...Detected 2 categorical features: ['cat_Seasons', 'cat_Holiday']
Detected 1 date features: ['dat_Date']

Detected 2 categorical features: ['cat_Seasons', 'cat_Holiday']
Detected 1 date features: ['dat_Date']
Detected task type: classification
Detected 10 numerical features: ['num_Rented Bike Count', 'num_Hour', 'num_Temperature', 'num_Humidity', 'num_Wind speed']...
Detected 2 categorical features: ['cat_Seasons', 'cat_Holiday']
Detected 1 date features: ['dat_Date']
Detected task type: classification
Detected 10 numerical features: ['num_Rented Bike Count', 'num_Hour', 'num_Temperature', 'num_Humidity', 'num_Wind speed']...
Detected 2 categorical features: ['cat_Seasons', 'cat_Holiday']
Detected 1 date features: ['dat_Date']
Detected task type: classification
Detected 10 numerical features: ['num_Rented Bike Count', 'num_Hour', 'num_Temperature', 'num_Humidity', 'num_Wind speed']...
Detected 2 categorical features: ['cat_Seasons', 'cat_Holiday']
Detected 1 date features: ['dat_Date']

Evaluating rice_cammeo_and_osmancik (classification)...
Detected task type: classification
Detected 7 numerical features: ['num_Area', 'num_Perimeter', 'num_Major_Axis_Length', 'num_Minor_Axis_Length', 'num_Eccentricity']...
Detected 0 categorical features: []
Detected task type: classification
Detected 7 numerical features: ['num_Area', 'num_Perimeter', 'num_Major_Axis_Length', 'num_Minor_Axis_Length', 'num_Eccentricity']...
Detected 0 categorical features: []
Detected task type: classification
Detected 7 numerical features: ['num_Area', 'num_Perimeter', 'num_Major_Axis_Length', 'num_Minor_Axis_Length', 'num_Eccentricity']...
Detected 0 categorical features: []
Detected task type: classification
Detected 7 numerical features: ['num_Area', 'num_Perimeter', 'num_Major_Axis_Length', 'num_Minor_Axis_Length', 'num_Eccentricity']...
Detected 0 categorical features: []
Detected task type: classification
Detected 7 numerical features: ['num_Area', 'num_Perimeter', 'num_Major_Axis_Length', 'num_Minor_Axis_Length', 'num_Eccentricity']...
Detected 0 categorical features: []
Detected task type: classification
Detected 7 numerical features: ['num_Area', 'num_Perimeter', 'num_Major_Axis_Length', 'num_Minor_Axis_Length', 'num_Eccentricity']...
Detected 0 categorical features: []
Detected task type: classification
Detected 7 numerical features: ['num_Area', 'num_Perimeter', 'num_Major_Axis_Length', 'num_Minor_Axis_Length', 'num_Eccentricity']...
Detected 0 categorical features: []
Detected task type: classification
Detected 7 numerical features: ['num_Area', 'num_Perimeter', 'num_Major_Axis_Length', 'num_Minor_Axis_Length', 'num_Eccentricity']...
Detected 0 categorical features: []
Detected task type: classification
Detected 7 numerical features: ['num_Area', 'num_Perimeter', 'num_Major_Axis_Length', 'num_Minor_Axis_Length', 'num_Eccentricity']...
Detected 0 categorical features: []
Detected task type: classification
Detected 7 numerical features: ['num_Area', 'num_Perimeter', 'num_Major_Axis_Length', 'num_Minor_Axis_Length', 'num_Eccentricity']...
Detected 0 categorical features: []
Detected task type: classification
Detected 7 numerical features: ['num_Area', 'num_Perimeter', 'num_Major_Axis_Length', 'num_Minor_Axis_Length', 'num_Eccentricity']...
Detected 0 categorical features: []
Detected task type: classification
Detected 7 numerical features: ['num_Area', 'num_Perimeter', 'num_Major_Axis_Length', 'num_Minor_Axis_Length', 'num_Eccentricity']...
Detected 0 categorical features: []
Detected task type: classification
Detected 7 numerical features: ['num_Area', 'num_Perimeter', 'num_Major_Axis_Length', 'num_Minor_Axis_Length', 'num_Eccentricity']...
Detected 0 categorical features: []
Detected task type: classification
Detected 7 numerical features: ['num_Area', 'num_Perimeter', 'num_Major_Axis_Length', 'num_Minor_Axis_Length', 'num_Eccentricity']...
Detected 0 categorical features: []
Detected task type: classification
Detected 7 numerical features: ['num_Area', 'num_Perimeter', 'num_Major_Axis_Length', 'num_Minor_Axis_Length', 'num_Eccentricity']...
Detected 0 categorical features: []

Evaluating optical_recognition_of_handwritten_digits (classification)...
Detected task type: classification
Detected 64 numerical features: ['num_Attribute1', 'num_Attribute2', 'num_Attribute3', 'num_Attribute4', 'num_Attribute5']...
Detected 0 categorical features: []
Detected task type: classification
Detected 64 numerical features: ['num_Attribute1', 'num_Attribute2', 'num_Attribute3', 'num_Attribute4', 'num_Attribute5']...
Detected 0 categorical features: []
Detected task type: classification
Detected 64 numerical features: ['num_Attribute1', 'num_Attribute2', 'num_Attribute3', 'num_Attribute4', 'num_Attribute5']...
Detected 0 categorical features: []
Detected task type: classification
Detected task type: classification
Detected 64 numerical features: ['num_Attribute1', 'num_Attribute2', 'num_Attribute3', 'num_Attribute4', 'num_Attribute5']...
Detected 0 categorical features: []
Detected 64 numerical features: ['num_Attribute1', 'num_Attribute2', 'num_Attribute3', 'num_Attribute4', 'num_Attribute5']...
Detected 0 categorical features: []
Detected task type: classification
Detected 64 numerical features: ['num_Attribute1', 'num_Attribute2', 'num_Attribute3', 'num_Attribute4', 'num_Attribute5']...
Detected 0 categorical features: []
Detected task type: classification
Detected 64 numerical features: ['num_Attribute1', 'num_Attribute2', 'num_Attribute3', 'num_Attribute4', 'num_Attribute5']...
Detected 0 categorical features: []
Detected task type: classification
Detected 64 numerical features: ['num_Attribute1', 'num_Attribute2', 'num_Attribute3', 'num_Attribute4', 'num_Attribute5']...
Detected 0 categorical features: []
Detected task type: classification
Detected 64 numerical features: ['num_Attribute1', 'num_Attribute2', 'num_Attribute3', 'num_Attribute4', 'num_Attribute5']...
Detected 0 categorical features: []
Detected task type: classification
Detected 64 numerical features: ['num_Attribute1', 'num_Attribute2', 'num_Attribute3', 'num_Attribute4', 'num_Attribute5']...
Detected 0 categorical features: []
Detected task type: classification
Detected 64 numerical features: ['num_Attribute1', 'num_Attribute2', 'num_Attribute3', 'num_Attribute4', 'num_Attribute5']...
Detected 0 categorical features: []
Detected task type: classification
Detected 64 numerical features: ['num_Attribute1', 'num_Attribute2', 'num_Attribute3', 'num_Attribute4', 'num_Attribute5']...
Detected 0 categorical features: []
Detected task type: classification
Detected 64 numerical features: ['num_Attribute1', 'num_Attribute2', 'num_Attribute3', 'num_Attribute4', 'num_Attribute5']...
Detected 0 categorical features: []
Detected task type: classification
Detected 64 numerical features: ['num_Attribute1', 'num_Attribute2', 'num_Attribute3', 'num_Attribute4', 'num_Attribute5']...
Detected 0 categorical features: []
Detected task type: classification
Detected 64 numerical features: ['num_Attribute1', 'num_Attribute2', 'num_Attribute3', 'num_Attribute4', 'num_Attribute5']...
Detected 0 categorical features: []

Evaluating glass_identification (classification)...
Detected task type: classification
Detected task type: classification
Detected task type: classification
Detected 9 numerical features: ['num_RI', 'num_Na', 'num_Mg', 'num_Al', 'num_Si']...
Detected 0 categorical features: []
Detected 9 numerical features: ['num_RI', 'num_Na', 'num_Mg', 'num_Al', 'num_Si']...
Detected 0 categorical features: []
Detected 9 numerical features: ['num_RI', 'num_Na', 'num_Mg', 'num_Al', 'num_Si']...
Detected 0 categorical features: []
Detected task type: classification
Detected 9 numerical features: ['num_RI', 'num_Na', 'num_Mg', 'num_Al', 'num_Si']...
Detected 0 categorical features: []
Detected task type: classification
Detected 9 numerical features: ['num_RI', 'num_Na', 'num_Mg', 'num_Al', 'num_Si']...
Detected 0 categorical features: []
Detected task type: classification
Detected 9 numerical features: ['num_RI', 'num_Na', 'num_Mg', 'num_Al', 'num_Si']...
Detected 0 categorical features: []
Detected task type: classification
Detected 9 numerical features: ['num_RI', 'num_Na', 'num_Mg', 'num_Al', 'num_Si']...
Detected 0 categorical features: []
Detected task type: classification
Detected task type: classification
Detected 9 numerical features: ['num_RI', 'num_Na', 'num_Mg', 'num_Al', 'num_Si']...
Detected 0 categorical features: []
Detected 9 numerical features: ['num_RI', 'num_Na', 'num_Mg', 'num_Al', 'num_Si']...
Detected 0 categorical features: []
Detected task type: classification
Detected 9 numerical features: ['num_RI', 'num_Na', 'num_Mg', 'num_Al', 'num_Si']...
Detected 0 categorical features: []
Detected task type: classification
Detected 9 numerical features: ['num_RI', 'num_Na', 'num_Mg', 'num_Al', 'num_Si']...
Detected 0 categorical features: []
Detected task type: classification
Detected 9 numerical features: ['num_RI', 'num_Na', 'num_Mg', 'num_Al', 'num_Si']...
Detected 0 categorical features: []
Detected task type: classification
Detected 9 numerical features: ['num_RI', 'num_Na', 'num_Mg', 'num_Al', 'num_Si']...
Detected 0 categorical features: []
Detected task type: classification
Detected 9 numerical features: ['num_RI', 'num_Na', 'num_Mg', 'num_Al', 'num_Si']...
Detected 0 categorical features: []
Detected task type: classification
Detected 9 numerical features: ['num_RI', 'num_Na', 'num_Mg', 'num_Al', 'num_Si']...
Detected 0 categorical features: []

Evaluating phishing_websites (regression)...
Detected task type: classification
Detected 30 numerical features: ['num_having_ip_address', 'num_url_length', 'num_shortining_service', 'num_having_at_symbol', 'num_double_slash_redirecting']...
Detected 0 categorical features: []
Detected task type: classification
Detected 30 numerical features: ['num_having_ip_address', 'num_url_length', 'num_shortining_service', 'num_having_at_symbol', 'num_double_slash_redirecting']...
Detected 0 categorical features: []
Detected task type: classificationDetected task type: classification
Detected 30 numerical features: ['num_having_ip_address', 'num_url_length', 'num_shortining_service', 'num_having_at_symbol', 'num_double_slash_redirecting']...
Detected 0 categorical features: []

Detected 30 numerical features: ['num_having_ip_address', 'num_url_length', 'num_shortining_service', 'num_having_at_symbol', 'num_double_slash_redirecting']...
Detected 0 categorical features: []
Detected task type: classification
Detected 30 numerical features: ['num_having_ip_address', 'num_url_length', 'num_shortining_service', 'num_having_at_symbol', 'num_double_slash_redirecting']...
Detected 0 categorical features: []
Detected task type: classification
Detected 30 numerical features: ['num_having_ip_address', 'num_url_length', 'num_shortining_service', 'num_having_at_symbol', 'num_double_slash_redirecting']...
Detected 0 categorical features: []
Detected task type: classification
Detected 30 numerical features: ['num_having_ip_address', 'num_url_length', 'num_shortining_service', 'num_having_at_symbol', 'num_double_slash_redirecting']...
Detected 0 categorical features: []
Detected task type: classification
Detected 30 numerical features: ['num_having_ip_address', 'num_url_length', 'num_shortining_service', 'num_having_at_symbol', 'num_double_slash_redirecting']...
Detected 0 categorical features: []
Detected task type: classification
Detected 30 numerical features: ['num_having_ip_address', 'num_url_length', 'num_shortining_service', 'num_having_at_symbol', 'num_double_slash_redirecting']...
Detected 0 categorical features: []
Detected task type: classification
Detected 30 numerical features: ['num_having_ip_address', 'num_url_length', 'num_shortining_service', 'num_having_at_symbol', 'num_double_slash_redirecting']...
Detected 0 categorical features: []
Detected task type: classification
Detected 30 numerical features: ['num_having_ip_address', 'num_url_length', 'num_shortining_service', 'num_having_at_symbol', 'num_double_slash_redirecting']...
Detected 0 categorical features: []
Detected task type: classification
Detected 30 numerical features: ['num_having_ip_address', 'num_url_length', 'num_shortining_service', 'num_having_at_symbol', 'num_double_slash_redirecting']...
Detected 0 categorical features: []
Detected task type: classification
Detected 30 numerical features: ['num_having_ip_address', 'num_url_length', 'num_shortining_service', 'num_having_at_symbol', 'num_double_slash_redirecting']...
Detected 0 categorical features: []
Detected task type: classification
Detected 30 numerical features: ['num_having_ip_address', 'num_url_length', 'num_shortining_service', 'num_having_at_symbol', 'num_double_slash_redirecting']...
Detected 0 categorical features: []
Detected task type: classification
Detected 30 numerical features: ['num_having_ip_address', 'num_url_length', 'num_shortining_service', 'num_having_at_symbol', 'num_double_slash_redirecting']...
Detected 0 categorical features: []

Evaluating appliances_energy_prediction (regression)...
Detected task type: classification
Detected 27 numerical features: ['num_lights', 'num_T1', 'num_RH_1', 'num_T2', 'num_RH_2']...
Detected 0 categorical features: []
Detected 1 date features: ['dat_date']
Detected task type: classification
Detected 27 numerical features: ['num_lights', 'num_T1', 'num_RH_1', 'num_T2', 'num_RH_2']...
Detected 0 categorical features: []
Detected 1 date features: ['dat_date']
Detected task type: classification
Detected 27 numerical features: ['num_lights', 'num_T1', 'num_RH_1', 'num_T2', 'num_RH_2']...
Detected 0 categorical features: []
Detected 1 date features: ['dat_date']
Detected task type: classification

/home/aarchetto/frog-dq/notebooks/../frogdq/preprocessing.py:323: FutureWarning: Downcasting behavior in Series and DataFrame methods 'where', 'mask', and 'clip' is deprecated. In a future version this will not infer object dtypes or cast all-round floats to integers. Instead call result.infer_objects(copy=False) for object inference, or cast round floats explicitly. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X[col] = X[col].clip(lower, upper).infer_objects(copy=False)
/home/aarchetto/frog-dq/notebooks/../frogdq/preprocessing.py:323: FutureWarning: Downcasting behavior in Series and DataFrame methods 'where', 'mask', and 'clip' is deprecated. In a future version this will not infer object dtypes or cast all-round floats to integers. Instead call result.infer_objects(copy=False) for object inference, or cast round floats explicitly. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X[col] = X[col].clip(lower, upper).infer_objects(copy=False)
/home/aarchetto/frog-dq/notebooks/../frogdq/preprocessing.py:323: FutureWarning: Downcasting behavior in Series and DataFrame methods 'where', 'mask', and 'clip' is deprecated. In a future version this will not infer object dtypes or cast all-round floats to integers. Instead call result.infer_objects(copy=False) for object inference, or cast round floats explicitly. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X[col] = X[col].clip(lower, upper).infer_objects(copy=False)
/home/aarchetto/frog-dq/notebooks/../frogdq/preprocessing.py:323: FutureWarning: Downcasting behavior in Series and DataFrame methods 'where', 'mask', and 'clip' is deprecated. In a future version this will not infer object dtypes or cast all-round floats to integers. Instead call result.infer_objects(copy=False) for object inference, or cast round floats explicitly. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X[col] = X[col].clip(lower, upper).infer_objects(copy=False)

Detected task type: regression
Detected 10 numerical features: ['num_team', 'num_targeted_productivity', 'num_smv', 'num_wip', 'num_over_time']...
Detected 3 categorical features: ['cat_quarter', 'cat_department', 'cat_day']
Detected 1 date features: ['dat_date']
Detected task type: regression
Detected 10 numerical features: ['num_team', 'num_targeted_productivity', 'num_smv', 'num_wip', 'num_over_time']...
Detected 3 categorical features: ['cat_quarter', 'cat_department', 'cat_day']
Detected 1 date features: ['dat_date']
Detected task type: regression
Detected 10 numerical features: ['num_team', 'num_targeted_productivity', 'num_smv', 'num_wip', 'num_over_time']...
Detected 3 categorical features: ['cat_quarter', 'cat_department', 'cat_day']
Detected 1 date features: ['dat_date']
Detected task type: regression
Detected 10 numerical features: ['num_team', 'num_targeted_productivity', 'num_smv', 'num_wip', 'num_over_time']...
Detected 3 categorical features: ['cat_quarter', 'cat_department', 'cat_day']
Detected 1 date features: ['dat_date']
Detected task type: regression
Detected 10 numerical features: ['num_team', 'num_targeted_productivity', 'num_smv', 'num_wip', 'num_over_time']...
Detected 3 categorical features: ['cat_quarter', 'cat_department', 'cat_day']
Detected 1 date features: ['dat_date']
Detected task type: regression
Detected 10 numerical features: ['num_team', 'num_targeted_productivity', 'num_smv', 'num_wip', 'num_over_time']...
Detected 3 categorical features: ['cat_quarter', 'cat_department', 'cat_day']
Detected 1 date features: ['dat_date']
Detected task type: regression
Detected 10 numerical features: ['num_team', 'num_targeted_productivity', 'num_smv', 'num_wip', 'num_over_time']...
Detected 3 categorical features: ['cat_quarter', 'cat_department', 'cat_day']
Detected 1 date features: ['dat_date']
Detected task type: regression
Detected 10 numerical features: ['num_team', 'num_targeted_productivity', 'num_smv', 'num_wip', 'num_over_time']...
Detected 3 categorical features: ['cat_quarter', 'cat_department', 'cat_day']
Detected 1 date features: ['dat_date']

Evaluating maternal_health_risk (classification)...
Detected task type: classificationDetected task type: classification
Detected 6 numerical features: ['num_Age', 'num_SystolicBP', 'num_DiastolicBP', 'num_BS', 'num_BodyTemp']...

Detected 0 categorical features: []
Detected 6 numerical features: ['num_Age', 'num_SystolicBP', 'num_DiastolicBP', 'num_BS', 'num_BodyTemp']...
Detected 0 categorical features: []Detected task type: classification

Detected 6 numerical features: ['num_Age', 'num_SystolicBP', 'num_DiastolicBP', 'num_BS', 'num_BodyTemp']...
Detected 0 categorical features: []
Detected task type: classification
Detected 6 numerical features: ['num_Age', 'num_SystolicBP', 'num_DiastolicBP', 'num_BS', 'num_BodyTemp']...
Detected 0 categorical features: []
Detected task type: classification
Detected 6 numerical features: ['num_Age', 'num_SystolicBP', 'num_DiastolicBP', 'num_BS', 'num_BodyTemp']...
Detected 0 categorical features: []
Detected task type: classification
Detected 6 numerical features: ['num_Age', 'num_SystolicBP', 'num_DiastolicBP', 'num_BS', 'num_BodyTemp']...
Detected 0 categorical features: []
Detected task type: classification
Detected 6 numerical features: ['num_Age', 'num_SystolicBP', 'num_DiastolicBP', 'num_BS', 'num_BodyTemp']...
Detected 0 categorical features: []
Detected task type: classification
Detected 6 numerical features: ['num_Age', 'num_SystolicBP', 'num_DiastolicBP', 'num_BS', 'num_BodyTemp']...
Detected 0 categorical features: []
Detected task type: classification
Detected 6 numerical features: ['num_Age', 'num_SystolicBP', 'num_DiastolicBP', 'num_BS', 'num_BodyTemp']...
Detected 0 categorical features: []
Detected task type: classification
Detected 6 numerical features: ['num_Age', 'num_SystolicBP', 'num_DiastolicBP', 'num_BS', 'num_BodyTemp']...
Detected 0 categorical features: []
Detected task type: classification
Detected 6 numerical features: ['num_Age', 'num_SystolicBP', 'num_DiastolicBP', 'num_BS', 'num_BodyTemp']...
Detected 0 categorical features: []
Detected task type: classification
Detected 6 numerical features: ['num_Age', 'num_SystolicBP', 'num_DiastolicBP', 'num_BS', 'num_BodyTemp']...
Detected 0 categorical features: []
Detected task type: classification
Detected 6 numerical features: ['num_Age', 'num_SystolicBP', 'num_DiastolicBP', 'num_BS', 'num_BodyTemp']...
Detected 0 categorical features: []
Detected task type: classification
Detected 6 numerical features: ['num_Age', 'num_SystolicBP', 'num_DiastolicBP', 'num_BS', 'num_BodyTemp']...
Detected 0 categorical features: []
Detected task type: classification
Detected 6 numerical features: ['num_Age', 'num_SystolicBP', 'num_DiastolicBP', 'num_BS', 'num_BodyTemp']...
Detected 0 categorical features: []

Evaluating early_stage_diabetes_risk_prediction (classification)...
Detected task type: classificationDetected task type: classification
Detected 1 numerical features: ['num_age']
Detected 15 categorical features: ['cat_gender', 'cat_polyuria', 'cat_polydipsia', 'cat_sudden_weight_loss', 'cat_weakness']...

Detected 1 numerical features: ['num_age']
Detected 15 categorical features: ['cat_gender', 'cat_polyuria', 'cat_polydipsia', 'cat_sudden_weight_loss', 'cat_weakness']...
Detected task type: classification
Detected 1 numerical features: ['num_age']
Detected 15 categorical features: ['cat_gender', 'cat_polyuria', 'cat_polydipsia', 'cat_sudden_weight_loss', 'cat_weakness']...
Detected task type: classification
Detected 1 numerical features: ['num_age']
Detected 15 categorical features: ['cat_gender', 'cat_polyuria', 'cat_polydipsia', 'cat_sudden_weight_loss', 'cat_weakness']...
Detected task type: classification
Detected 1 numerical features: ['num_age']
Detected 15 categorical features: ['cat_gender', 'cat_polyuria', 'cat_polydipsia', 'cat_sudden_weight_loss', 'cat_weakness']...
Detected task type: classification
Detected 1 numerical features: ['num_age']
Detected 15 categorical features: ['cat_gender', 'cat_polyuria', 'cat_polydipsia', 'cat_sudden_weight_loss', 'cat_weakness']...
Detected task type: classification
Detected 1 numerical features: ['num_age']
Detected 15 categorical features: ['cat_gender', 'cat_polyuria', 'cat_polydipsia', 'cat_sudden_weight_loss', 'cat_weakness']...
Detected task type: classification
Detected 1 numerical features: ['num_age']
Detected 15 categorical features: ['cat_gender', 'cat_polyuria', 'cat_polydipsia', 'cat_sudden_weight_loss', 'cat_weakness']...
Detected task type: classification
Detected 1 numerical features: ['num_age']
Detected 15 categorical features: ['cat_gender', 'cat_polyuria', 'cat_polydipsia', 'cat_sudden_weight_loss', 'cat_weakness']...
Detected task type: classification
Detected 1 numerical features: ['num_age']
Detected 15 categorical features: ['cat_gender', 'cat_polyuria', 'cat_polydipsia', 'cat_sudden_weight_loss', 'cat_weakness']...
Detected task type: classification
Detected 1 numerical features: ['num_age']
Detected 15 categorical features: ['cat_gender', 'cat_polyuria', 'cat_polydipsia', 'cat_sudden_weight_loss', 'cat_weakness']...
Detected task type: classification
Detected 1 numerical features: ['num_age']
Detected 15 categorical features: ['cat_gender', 'cat_polyuria', 'cat_polydipsia', 'cat_sudden_weight_loss', 'cat_weakness']...
Detected task type: classification
Detected 1 numerical features: ['num_age']
Detected 15 categorical features: ['cat_gender', 'cat_polyuria', 'cat_polydipsia', 'cat_sudden_weight_loss', 'cat_weakness']...
Detected task type: classification
Detected 1 numerical features: ['num_age']
Detected 15 categorical features: ['cat_gender', 'cat_polyuria', 'cat_polydipsia', 'cat_sudden_weight_loss', 'cat_weakness']...
Detected task type: classification
Detected 1 numerical features: ['num_age']
Detected 15 categorical features: ['cat_gender', 'cat_polyuria', 'cat_polydipsia', 'cat_sudden_weight_loss', 'cat_weakness']...

Evaluating letter_recognition (classification)...
Detected task type: classification
Detected 16 numerical features: ['num_x-box', 'num_y-box', 'num_width', 'num_high', 'num_onpix']...
Detected 0 categorical features: []
Detected task type: classification
Detected task type: classification
Detected 16 numerical features: ['num_x-box', 'num_y-box', 'num_width', 'num_high', 'num_onpix']...Detected 16 numerical features: ['num_x-box', 'num_y-box', 'num_width', 'num_high', 'num_onpix']...
Detected 0 categorical features: []

Detected 0 categorical features: []
Detected task type: classification
Detected 16 numerical features: ['num_x-box', 'num_y-box', 'num_width', 'num_high', 'num_onpix']...
Detected 0 categorical features: []
Detected task type: classification
Detected 16 numerical features: ['num_x-box', 'num_y-box', 'num_width', 'num_high', 'num_onpix']...
Detected 0 categorical features: []
Detected task type: classification
Detected 16 numerical features: ['num_x-box', 'num_y-box', 'num_width', 'num_high', 'num_onpix']...
Detected 0 categorical features: []
Detected task type: classification
Detected 16 numerical features: ['num_x-box', 'num_y-box', 'num_width', 'num_high', 'num_onpix']...
Detected 0 categorical features: []
Detected task type: classification
Detected 16 numerical features: ['num_x-box', 'num_y-box', 'num_width', 'num_high', 'num_onpix']...
Detected 0 categorical features: []
Detected task type: classification
Detected 16 numerical features: ['num_x-box', 'num_y-box', 'num_width', 'num_high', 'num_onpix']...
Detected 0 categorical features: []
Detected task type: classification
Detected 16 numerical features: ['num_x-box', 'num_y-box', 'num_width', 'num_high', 'num_onpix']...
Detected 0 categorical features: []
Detected task type: classification
Detected 16 numerical features: ['num_x-box', 'num_y-box', 'num_width', 'num_high', 'num_onpix']...
Detected 0 categorical features: []
Detected task type: classification
Detected 16 numerical features: ['num_x-box', 'num_y-box', 'num_width', 'num_high', 'num_onpix']...
Detected 0 categorical features: []
Detected task type: classification
Detected 16 numerical features: ['num_x-box', 'num_y-box', 'num_width', 'num_high', 'num_onpix']...
Detected 0 categorical features: []
Detected task type: classification
Detected 16 numerical features: ['num_x-box', 'num_y-box', 'num_width', 'num_high', 'num_onpix']...
Detected 0 categorical features: []
Detected task type: classification
Detected 16 numerical features: ['num_x-box', 'num_y-box', 'num_width', 'num_high', 'num_onpix']...
Detected 0 categorical features: []

Evaluating combined_cycle_power_plant (regression)...
Detected task type: regression
Detected 4 numerical features: ['num_AT', 'num_V', 'num_AP', 'num_RH']
Detected 0 categorical features: []
Detected task type: regression
Detected 4 numerical features: ['num_AT', 'num_V', 'num_AP', 'num_RH']
Detected 0 categorical features: []
Detected task type: regression
Detected 4 numerical features: ['num_AT', 'num_V', 'num_AP', 'num_RH']
Detected 0 categorical features: []
Detected task type: regression
Detected 4 numerical features: ['num_AT', 'num_V', 'num_AP', 'num_RH']
Detected 0 categorical features: []
Detected task type: regression
Detected 4 numerical features: ['num_AT', 'num_V', 'num_AP', 'num_RH']
Detected 0 categorical features: []
Detected task type: regression
Detected 4 numerical features: ['num_AT', 'num_V', 'num_AP', 'num_RH']
Detected 0 categorical features: []
Detected task type: regression
Detected 4 numerical features: ['num_AT', 'num_V', 'num_AP', 'num_RH']
Detected 0 categorical features: []
Detected task type: regression
Detected 4 numerical features: ['num_AT', 'num_V', 'num_AP', 'num_RH']
Detected 0 categorical features: []
Detected task type: regression
Detected 4 numerical features: ['num_AT', 'num_V', 'num_AP', 'num_RH']
Detected 0 categorical features: []
Detected task type: regression
Detected 4 numerical features: ['num_AT', 'num_V', 'num_AP', 'num_RH']
Detected 0 categorical features: []
Detected task type: regression
Detected 4 numerical features: ['num_AT', 'num_V', 'num_AP', 'num_RH']
Detected 0 categorical features: []
Detected task type: regression
Detected 4 numerical features: ['num_AT', 'num_V', 'num_AP', 'num_RH']
Detected 0 categorical features: []
Detected task type: regression
Detected 4 numerical features: ['num_AT', 'num_V', 'num_AP', 'num_RH']
Detected 0 categorical features: []
Detected task type: regression
Detected 4 numerical features: ['num_AT', 'num_V', 'num_AP', 'num_RH']
Detected 0 categorical features: []
Detected task type: regression
Detected 4 numerical features: ['num_AT', 'num_V', 'num_AP', 'num_RH']
Detected 0 categorical features: []

Evaluating liver_disorders (regression)...
Detected task type: regression
Detected 5 numerical features: ['num_mcv', 'num_alkphos', 'num_sgpt', 'num_sgot', 'num_gammagt']
Detected 0 categorical features: []
Detected task type: regression
Detected task type: regressionDetected 5 numerical features: ['num_mcv', 'num_alkphos', 'num_sgpt', 'num_sgot', 'num_gammagt']

Detected 0 categorical features: []
Detected 5 numerical features: ['num_mcv', 'num_alkphos', 'num_sgpt', 'num_sgot', 'num_gammagt']
Detected 0 categorical features: []
Detected task type: regression
Detected 5 numerical features: ['num_mcv', 'num_alkphos', 'num_sgpt', 'num_sgot', 'num_gammagt']
Detected 0 categorical features: []
Detected task type: regression
Detected 5 numerical features: ['num_mcv', 'num_alkphos', 'num_sgpt', 'num_sgot', 'num_gammagt']
Detected 0 categorical features: []
Detected task type: regression
Detected 5 numerical features: ['num_mcv', 'num_alkphos', 'num_sgpt', 'num_sgot', 'num_gammagt']
Detected 0 categorical features: []
Detected task type: regression
Detected 5 numerical features: ['num_mcv', 'num_alkphos', 'num_sgpt', 'num_sgot', 'num_gammagt']
Detected 0 categorical features: []
Detected task type: regression
Detected 5 numerical features: ['num_mcv', 'num_alkphos', 'num_sgpt', 'num_sgot', 'num_gammagt']
Detected 0 categorical features: []
Detected task type: regression
Detected 5 numerical features: ['num_mcv', 'num_alkphos', 'num_sgpt', 'num_sgot', 'num_gammagt']
Detected 0 categorical features: []
Detected task type: regression
Detected 5 numerical features: ['num_mcv', 'num_alkphos', 'num_sgpt', 'num_sgot', 'num_gammagt']
Detected 0 categorical features: []
Detected task type: regression
Detected 5 numerical features: ['num_mcv', 'num_alkphos', 'num_sgpt', 'num_sgot', 'num_gammagt']
Detected 0 categorical features: []
Detected task type: regression
Detected 5 numerical features: ['num_mcv', 'num_alkphos', 'num_sgpt', 'num_sgot', 'num_gammagt']
Detected 0 categorical features: []
Detected task type: regression
Detected 5 numerical features: ['num_mcv', 'num_alkphos', 'num_sgpt', 'num_sgot', 'num_gammagt']
Detected 0 categorical features: []
Detected task type: regression
Detected 5 numerical features: ['num_mcv', 'num_alkphos', 'num_sgpt', 'num_sgot', 'num_gammagt']
Detected 0 categorical features: []
Detected task type: regression
Detected 5 numerical features: ['num_mcv', 'num_alkphos', 'num_sgpt', 'num_sgot', 'num_gammagt']
Detected 0 categorical features: []

Evaluating national_poll_on_healthy_aging_npha (classification)...
Detected task type: classificationDetected task type: classification
Detected 0 numerical features: []
Detected 14 categorical features: ['cat_Age', 'cat_Physical_Health', 'cat_Mental_Health', 'cat_Dental_Health', 'cat_Employment']...

Detected 0 numerical features: []
Detected 14 categorical features: ['cat_Age', 'cat_Physical_Health', 'cat_Mental_Health', 'cat_Dental_Health', 'cat_Employment']...
Detected task type: classification
Detected 0 numerical features: []
Detected 14 categorical features: ['cat_Age', 'cat_Physical_Health', 'cat_Mental_Health', 'cat_Dental_Health', 'cat_Employment']...
Detected task type: classification
Detected 0 numerical features: []
Detected 14 categorical features: ['cat_Age', 'cat_Physical_Health', 'cat_Mental_Health', 'cat_Dental_Health', 'cat_Employment']...
Detected task type: classification
Detected 0 numerical features: []
Detected 14 categorical features: ['cat_Age', 'cat_Physical_Health', 'cat_Mental_Health', 'cat_Dental_Health', 'cat_Employment']...
Detected task type: classification
Detected 0 numerical features: []
Detected 14 categorical features: ['cat_Age', 'cat_Physical_Health', 'cat_Mental_Health', 'cat_Dental_Health', 'cat_Employment']...
Detected task type: classification
Detected 0 numerical features: []
Detected 14 categorical features: ['cat_Age', 'cat_Physical_Health', 'cat_Mental_Health', 'cat_Dental_Health', 'cat_Employment']...
Detected task type: classification
Detected 0 numerical features: []
Detected 14 categorical features: ['cat_Age', 'cat_Physical_Health', 'cat_Mental_Health', 'cat_Dental_Health', 'cat_Employment']...
Detected task type: classification
Detected 0 numerical features: []
Detected 14 categorical features: ['cat_Age', 'cat_Physical_Health', 'cat_Mental_Health', 'cat_Dental_Health', 'cat_Employment']...
Detected task type: classification
Detected 0 numerical features: []
Detected 14 categorical features: ['cat_Age', 'cat_Physical_Health', 'cat_Mental_Health', 'cat_Dental_Health', 'cat_Employment']...
Detected task type: classification
Detected 0 numerical features: []
Detected 14 categorical features: ['cat_Age', 'cat_Physical_Health', 'cat_Mental_Health', 'cat_Dental_Health', 'cat_Employment']...Detected task type: classification
Detected 0 numerical features: []
Detected 14 categorical features: ['cat_Age', 'cat_Physical_Health', 'cat_Mental_Health', 'cat_Dental_Health', 'cat_Employment']...

Detected task type: classification
Detected 0 numerical features: []
Detected 14 categorical features: ['cat_Age', 'cat_Physical_Health', 'cat_Mental_Health', 'cat_Dental_Health', 'cat_Employment']...
Detected task type: classification
Detected 0 numerical features: []
Detected 14 categorical features: ['cat_Age', 'cat_Physical_Health', 'cat_Mental_Health', 'cat_Dental_Health', 'cat_Employment']...
Detected task type: classification
Detected 0 numerical features: []
Detected 14 categorical features: ['cat_Age', 'cat_Physical_Health', 'cat_Mental_Health', 'cat_Dental_Health', 'cat_Employment']...

Evaluating hepatitis (classification)...
Detected task type: classification
Detected task type: classificationDetected 7 numerical features: ['num_Age', 'num_Bilirubin', 'num_Alk Phosphate', 'num_Sgot', 'num_Albumin']...
Detected 12 categorical features: ['cat_Sex', 'cat_Steroid', 'cat_Antivirals', 'cat_Fatigue', 'cat_Malaise']...

Detected 7 numerical features: ['num_Age', 'num_Bilirubin', 'num_Alk Phosphate', 'num_Sgot', 'num_Albumin']...
Detected 12 categorical features: ['cat_Sex', 'cat_Steroid', 'cat_Antivirals', 'cat_Fatigue', 'cat_Malaise']...
Detected task type: classification
Detected 7 numerical features: ['num_Age', 'num_Bilirubin', 'num_Alk Phosphate', 'num_Sgot', 'num_Albumin']...
Detected task type: classificationDetected 12 categorical features: ['cat_Sex', 'cat_Steroid', 'cat_Antivirals', 'cat_Fatigue', 'cat_Malaise']...

Detected 7 numerical features: ['num_Age', 'num_Bilirubin', 'num_Alk Phosphate', 'num_Sgot', 'num_Albumin']...
Detected 12 categorical features: ['cat_Sex', 'cat_Steroid', 'cat_Antivirals', 'cat_Fatigue', 'cat_Malaise']...
Detected task type: classification
Detected 7 numerical features: ['num_Age', 'num_Bilirubin', 'num_Alk Phosphate', 'num_Sgot', 'num_Albumin']...
Detected 12 categorical features: ['cat_Sex', 'cat_Steroid', 'cat_Antivirals', 'cat_Fatigue', 'cat_Malaise']...
Detected task type: classification
Detected 7 numerical features: ['num_Age', 'num_Bilirubin', 'num_Alk Phosphate', 'num_Sgot', 'num_Albumin']...
Detected 12 categorical features: ['cat_Sex', 'cat_Steroid', 'cat_Antivirals', 'cat_Fatigue', 'cat_Malaise']...
Detected task type: classification

## Results Overview

In [10]:
# Display first few results
results_df.head(20)

,dataset,task_type,data_mode,seed,model,overall_quality,train_samples,test_samples,accuracy,f1_score,mse,r2_score
0,iris,classification,clean,42,LogisticRegression,100.0,90,30,0.933333,0.933333,NaN,NaN
1,iris,classification,clean,42,DecisionTree,100.0,90,30,0.933333,0.933333,NaN,NaN
2,iris,classification,clean,42,RandomForest,100.0,90,30,0.933333,0.933333,NaN,NaN
3,iris,classification,clean,42,KNN,100.0,90,30,0.966667,0.966583,NaN,NaN
4,iris,classification,clean,43,LogisticRegression,100.0,90,30,0.966667,0.966583,NaN,NaN
5,iris,classification,clean,43,DecisionTree,100.0,90,30,1.000000,1.000000,NaN,NaN
6,iris,classification,clean,43,RandomForest,100.0,90,30,0.966667,0.966583,NaN,NaN
7,iris,classification,clean,43,KNN,100.0,90,30,0.933333,0.932660,NaN,NaN
8,iris,classification,clean,44,LogisticRegression,100.0,90,30,0.966667,0.966583,NaN,NaN
9,iris,classification,clean,44,DecisionTree,100.0,90,30,0.966667,0.966583,NaN,NaN
10,iris,classification,clean,44,RandomForest,100.0,90,30,0.966667,0.966583,NaN,NaN
11,iris,classification,clean,44,KNN,100.0,90,30,0.966667,0.966583,NaN,NaN
12,iris,classification,clean,45,LogisticRegression,100.0,90,30,0.900000,0.899749,NaN,NaN
13,iris,classification,clean,45,DecisionTree,100.0,90,30,0.933333,0.932660,NaN,NaN
14,iris,classification,clean,45,RandomForest,100.0,90,30,0.900000,0.899749,NaN,NaN
15,iris,classification,clean,45,KNN,100.0,90,30,0.933333,0.932660,NaN,NaN
16,iris,classification,clean,46,LogisticRegression,100.0,90,30,0.966667,0.966583,NaN,NaN
17,iris,classification,clean,46,DecisionTree,100.0,90,30,0.966667,0.966583,NaN,NaN
18,iris,classification,clean,46,RandomForest,100.0,90,30,0.933333,0.932660,NaN,NaN
19,iris,classification,clean,46,KNN,100.0,90,30,0.966667,0.966583,NaN,NaN

## Summary Statistics Across Seeds

In [12]:
# Summary statistics for classification tasks
if "accuracy" in results_df.columns:
    cls_results = results_df[results_df["task_type"] == "classification"].copy()

    print("\n" + "=" * 60)
    print("CLASSIFICATION TASKS SUMMARY (Averaged Across Seeds)")
    print("=" * 60)

    summary = cls_results.groupby(["data_mode", "model"])[["accuracy", "f1_score"]].agg(
        ["mean", "std"]
    )
    print(summary)

============================================================
CLASSIFICATION TASKS SUMMARY (Averaged Across Seeds)
============================================================
                              accuracy            f1_score
                                  mean       std      mean       std
data_mode model
ar        DecisionTree        0.769501  0.196240  0.753498  0.227555
          KNN                 0.788892  0.195531  0.768150  0.223002
          LogisticRegression  0.799948  0.179302  0.773704  0.216741
          RandomForest        0.818163  0.177725  0.790882  0.218754
clean     DecisionTree        0.812184  0.167322  0.805942  0.176831
          KNN                 0.814504  0.171011  0.801425  0.183684
          LogisticRegression  0.829758  0.164176  0.813245  0.182373
          RandomForest        0.853044  0.153199  0.837334  0.176084
nar       DecisionTree        0.757028  0.200328  0.742794  0.224326
          KNN                 0.781969  0.192176  0.761773  0.220063
          LogisticRegression  0.796087  0.182043  0.769348  0.219447
          RandomForest        0.808933  0.175683  0.779384  0.218436

In [13]:
# Summary statistics for regression tasks
if "r2_score" in results_df.columns:
    reg_results = results_df[results_df["task_type"] == "regression"].copy()

    print("\n" + "=" * 60)
    print("REGRESSION TASKS SUMMARY (Averaged Across Seeds)")
    print("=" * 60)

    summary = reg_results.groupby(["data_mode", "model"])[["r2_score"]].agg(
        ["mean", "std"]
    )
    print(summary)

============================================================
REGRESSION TASKS SUMMARY (Averaged Across Seeds)
============================================================
                        r2_score
                            mean       std
data_mode model
ar        DecisionTree  0.301235  0.491534
          KNN           0.484427  0.316563
          RandomForest  0.540666  0.308633
          Ridge         0.436411  0.302851
clean     DecisionTree  0.126492  1.990773
          KNN           0.479150  0.515825
          RandomForest  0.526416  0.631822
          Ridge         0.490285  0.300226
nar       DecisionTree  0.063664  1.758892
          KNN           0.420634  0.535404
          RandomForest  0.458644  0.526925
          Ridge         0.424649  0.301014

## Performance Degradation Analysis

In [14]:
# Calculate performance degradation for classification
if "accuracy" in results_df.columns:
    cls_results = results_df[results_df["task_type"] == "classification"].copy()

    print("\n" + "=" * 60)
    print("CLASSIFICATION: Performance Degradation (Accuracy)")
    print("=" * 60)

    # Create pivot table with multi-level aggregation
    pivot = cls_results.pivot_table(
        index=["dataset", "model", "seed"],
        columns="data_mode",
        values="accuracy",
    )

    if "clean" in pivot.columns:
        if "ar" in pivot.columns:
            pivot["ar_degradation"] = pivot["clean"] - pivot["ar"]
        if "nar" in pivot.columns:
            pivot["nar_degradation"] = pivot["clean"] - pivot["nar"]

    print("\nDegradation Statistics (averaged across seeds and datasets):")
    print(pivot[[col for col in pivot.columns if "degradation" in col]].describe())
    
    # Average across seeds for cleaner view
    pivot_avg = pivot.groupby(["dataset", "model"]).mean()
    print("\nTop 10 datasets with highest NAR degradation:")
    if "nar_degradation" in pivot_avg.columns:
        top_degraded = pivot_avg.nlargest(10, "nar_degradation")
        print(top_degraded[["clean", "nar", "nar_degradation"]])

============================================================
CLASSIFICATION: Performance Degradation (Accuracy)
============================================================

Degradation Statistics (averaged across seeds and datasets):
data_mode  ar_degradation  nar_degradation
count          680.000000       680.000000
mean             0.033246         0.041368
std              0.111327         0.116823
min             -0.153846        -0.153846
25%              0.000000         0.000000
50%              0.003686         0.008980
75%              0.028120         0.046922
max              0.809524         0.857143

Top 10 datasets with highest NAR degradation:
data_mode                                                                 clean  \
dataset                                            model
zoo                                                DecisionTree        0.933333
                                                   RandomForest        0.961905
                                                   KNN                 0.857143
                                                   LogisticRegression  0.942857
car_evaluation                                     DecisionTree        0.951445
                                                   RandomForest        0.939306
iranian_churn                                      DecisionTree        0.939048
estimation_of_obesity_levels_based_on_eating_ha... LogisticRegression  0.869976
car_evaluation                                     LogisticRegression  0.908092
                                                   KNN                 0.877457

data_mode                                                                   nar  \
dataset                                            model
zoo                                                DecisionTree        0.123810
                                                   RandomForest        0.380952
                                                   KNN                 0.295238
                                                   LogisticRegression  0.380952
car_evaluation                                     DecisionTree        0.744509
                                                   RandomForest        0.778613
iranian_churn                                      DecisionTree        0.789524
estimation_of_obesity_levels_based_on_eating_ha... LogisticRegression  0.734279
car_evaluation                                     LogisticRegression  0.779769
                                                   KNN                 0.760116

data_mode                                                              nar_degradation
dataset                                            model
zoo                                                DecisionTree               0.809524
                                                   RandomForest               0.580952
                                                   KNN                        0.561905
                                                   LogisticRegression         0.561905
car_evaluation                                     DecisionTree               0.206936
                                                   RandomForest               0.160694
iranian_churn                                      DecisionTree               0.149524
estimation_of_obesity_levels_based_on_eating_ha... LogisticRegression         0.135697
car_evaluation                                     LogisticRegression         0.128324
                                                   KNN                        0.117341

In [15]:
# Calculate performance degradation for regression
if "r2_score" in results_df.columns:
    reg_results = results_df[results_df["task_type"] == "regression"].copy()

    print("\n" + "=" * 60)
    print("REGRESSION: Performance Degradation (R2 Score)")
    print("=" * 60)

    pivot = reg_results.pivot_table(
        index=["dataset", "model", "seed"],
        columns="data_mode",
        values="r2_score",
    )

    if "clean" in pivot.columns:
        if "ar" in pivot.columns:
            pivot["ar_degradation"] = pivot["clean"] - pivot["ar"]
        if "nar" in pivot.columns:
            pivot["nar_degradation"] = pivot["clean"] - pivot["nar"]

    print("\nDegradation Statistics (averaged across seeds and datasets):")
    print(pivot[[col for col in pivot.columns if "degradation" in col]].describe())
    
    # Average across seeds for cleaner view
    pivot_avg = pivot.groupby(["dataset", "model"]).mean()
    print("\nTop 10 datasets with highest NAR degradation:")
    if "nar_degradation" in pivot_avg.columns:
        top_degraded = pivot_avg.nlargest(10, "nar_degradation")
        print(top_degraded[["clean", "nar", "nar_degradation"]])

============================================================
REGRESSION: Performance Degradation (R2 Score)
============================================================

Degradation Statistics (averaged across seeds and datasets):
data_mode  ar_degradation  nar_degradation
count          320.000000       320.000000
mean            -0.035099         0.063688
std              0.957131         0.238110
min            -16.018831        -2.044379
25%              0.000162         0.010642
50%              0.016722         0.037646
75%              0.049855         0.093786
max              0.592850         1.604443

Top 10 datasets with highest NAR degradation:
data_mode                                     clean       nar  nar_degradation
dataset                      model
bike_sharing                 RandomForest  0.743012  0.279847         0.463165
                             DecisionTree  0.658940  0.207832         0.451108
                             Ridge         0.680379  0.241150         0.439229
                             KNN           0.555143  0.235001         0.320142
automobile                   DecisionTree  0.622623  0.343368         0.279255
parkinsons                   DecisionTree  0.448621  0.204775         0.243846
appliances_energy_prediction RandomForest  0.356875  0.192880         0.163995
automobile                   Ridge         0.609892  0.452293         0.157599
real_estate_valuation        DecisionTree  0.342705  0.189574         0.153131
parkinsons                   Ridge         0.429288  0.298440         0.130848

## Model Comparison Across Data Modes

In [16]:
# Average performance by model and data mode (across all seeds)
if "accuracy" in results_df.columns:
    print("\nClassification: Average Accuracy by Model and Data Mode (Across Seeds)")
    print("=" * 60)
    cls_pivot = results_df[results_df["task_type"] == "classification"].pivot_table(
        index="model", columns="data_mode", values="accuracy", aggfunc="mean"
    )
    print(cls_pivot.round(4))

if "r2_score" in results_df.columns:
    print("\nRegression: Average R2 Score by Model and Data Mode (Across Seeds)")
    print("=" * 60)
    reg_pivot = results_df[results_df["task_type"] == "regression"].pivot_table(
        index="model", columns="data_mode", values="r2_score", aggfunc="mean"
    )
    print(reg_pivot.round(4))

Classification: Average Accuracy by Model and Data Mode (Across Seeds)
============================================================
data_mode               ar   clean     nar
model
DecisionTree        0.7695  0.8122  0.7570
KNN                 0.7889  0.8145  0.7820
LogisticRegression  0.7999  0.8298  0.7961
RandomForest        0.8182  0.8530  0.8089

Regression: Average R2 Score by Model and Data Mode (Across Seeds)
============================================================
data_mode         ar   clean     nar
model
DecisionTree  0.3012  0.1265  0.0637
KNN           0.4844  0.4792  0.4206
RandomForest  0.5407  0.5264  0.4586
Ridge         0.4364  0.4903  0.4246

## Variance Across Seeds

In [17]:
# Analyze variance in results across different seeds
print("\n" + "=" * 60)
print("VARIANCE ACROSS SEEDS")
print("=" * 60)

if "accuracy" in results_df.columns:
    cls_variance = results_df[results_df["task_type"] == "classification"].groupby(
        ["dataset", "data_mode", "model"]
    )["accuracy"].agg(["mean", "std"])
    
    print("\nClassification - Datasets with highest variance across seeds:")
    print(cls_variance.nlargest(10, "std"))

if "r2_score" in results_df.columns:
    reg_variance = results_df[results_df["task_type"] == "regression"].groupby(
        ["dataset", "data_mode", "model"]
    )["r2_score"].agg(["mean", "std"])
    
    print("\nRegression - Datasets with highest variance across seeds:")
    print(reg_variance.nlargest(10, "std"))

============================================================
VARIANCE ACROSS SEEDS
============================================================

Classification - Datasets with highest variance across seeds:
                                                                                   mean  \
dataset                                          data_mode model
national_poll_on_healthy_aging_npha              ar        DecisionTree        0.409790
                                                           KNN                 0.455944
                                                 nar       KNN                 0.453147
zoo                                              ar        KNN                 0.295238
                                                 nar       KNN                 0.295238
national_poll_on_healthy_aging_npha              nar       RandomForest        0.476923
                                                           LogisticRegression  0.476923
higher_education_students_performance_evaluation nar       DecisionTree        0.200000
glass_identification                             nar       KNN                 0.586047
higher_education_students_performance_evaluation clean     KNN                 0.262069

                                                                                    std
dataset                                          data_mode model
national_poll_on_healthy_aging_npha              ar        DecisionTree        0.161945
                                                           KNN                 0.153241
                                                 nar       KNN                 0.151718
zoo                                              ar        KNN                 0.118570
                                                 nar       KNN                 0.118570
national_poll_on_healthy_aging_npha              nar       RandomForest        0.102466
                                                           LogisticRegression  0.102466
higher_education_students_performance_evaluation nar       DecisionTree        0.095686
glass_identification                             nar       KNN                 0.093603
higher_education_students_performance_evaluation clean     KNN                 0.093167

Regression - Datasets with highest variance across seeds:
                                            mean       std
dataset         data_mode model
forest_fires    clean     DecisionTree -3.497548  7.407150
                nar       DecisionTree -3.469842  6.324508
                clean     RandomForest -1.066254  1.783430
                nar       KNN          -0.751504  1.499714
                clean     KNN          -0.648728  1.423474
                nar       RandomForest -0.884818  1.197165
liver_disorders clean     DecisionTree -1.138474  0.617602
                ar        DecisionTree -0.862490  0.554830
heart_disease   clean     DecisionTree -0.186235  0.416086
parkinsons      clean     DecisionTree  0.448621  0.355292